/**
 * StoryEditForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L28 (stories)
 * Generated: 2026-03-11T15:12:18Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for editing existing stories records with validation and error handling.
 * 
 * Features:
 * - Pre-populated with existing values
 * - Client-side validation
 * - Field-level error messages
 * - Update/Cancel actions
 * - Accessible form markup
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState, useEffect } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { updateStoryRecord } from '@api/storiesApi';
import type { StoryRecord, UpdateStoryRecordInput } from '@/types/stories';

interface StoryEditFormProps {
  record: StoryRecord;
  onSuccess: (record: StoryRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const StoryEditForm: React.FC<StoryEditFormProps> = ({ record, onSuccess, onCancel }) => {
  const t = useLiterals('stories.edit_form');

  const [formData, setFormData] = useState<Partial<UpdateStoryRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  // Initialize form data with existing record values
  useEffect(() => {
    const { layer, partition_key, _attachments, _etag, _rid, _self, _ts, ...editable } = record as any;
    setFormData(editable);
  }, [record]);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
        if (!formData.label) {
      newErrors.label = t('errors.required');
    }
    if (!formData.description) {
      newErrors.description = t('errors.required');
    }
    if (!formData.project_id) {
      newErrors.project_id = t('errors.required');
    }
    if (!formData.sprint_id) {
      newErrors.sprint_id = t('errors.required');
    }
    if (!formData.type) {
      newErrors.type = t('errors.required');
    }
    if (!formData.priority) {
      newErrors.priority = t('errors.required');
    }
    if (!formData.story_points) {
      newErrors.story_points = t('errors.required');
    }
    if (!formData.status) {
      newErrors.status = t('errors.required');
    }
    if (!formData.acceptance_criteria) {
      newErrors.acceptance_criteria = t('errors.required');
    }
    if (!formData.assigned_to) {
      newErrors.assigned_to = t('errors.required');
    }
    if (!formData.ado_work_item_id) {
      newErrors.ado_work_item_id = t('errors.required');
    }
    if (!formData.is_active) {
      newErrors.is_active = t('errors.required');
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const hasChanges = (): boolean => {
    const { layer, partition_key, _attachments, _etag, _rid, _self, _ts, ...original } = record as any;
    return JSON.stringify(formData) !== JSON.stringify(original);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!hasChanges()) {
      setSubmitError(t.noChanges);
      return;
    }

    if (!validate()) return;

    setSubmitting(true);
    try {
      const updated = await updateStoryRecord(
        record.id,
        formData as UpdateStoryRecordInput
      );
      onSuccess(updated);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="stories-edit-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <div style={{ marginBottom: 24 }}>
        <h2 style={{ margin: '0 0 4px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
          {t.title}
        </h2>
        <p style={{ margin: 0, fontSize: '0.75rem', color: GC_MUTED }}>
          L28: {record.id}
        </p>
      </div>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="stories-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t.error}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="label"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Label *
          </label>
          <input
            type="text"
            id="label"
            data-testid="stories-field-label"
            value={(formData.label as string) || ''}
            onChange={(e) => handleChange('label', e.target.value)}
            aria-invalid={!!errors.label}
            aria-describedby={errors.label ? 'label-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.label ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.label && (
            <div
              id="label-error"
              role="alert"
              data-testid="stories-field-label-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.label}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="description"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Description *
          </label>
          <textarea
            id="description"
            data-testid="stories-field-description"
            value={(formData.description as string) || ''}
            onChange={(e) => handleChange('description', e.target.value)}
            aria-invalid={!!errors.description}
            aria-describedby={errors.description ? 'description-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.description ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.description && (
            <div
              id="description-error"
              role="alert"
              data-testid="stories-field-description-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.description}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="project_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Project Id *
          </label>
          <input
            type="text"
            id="project_id"
            data-testid="stories-field-project_id"
            value={(formData.project_id as string) || ''}
            onChange={(e) => handleChange('project_id', e.target.value)}
            aria-invalid={!!errors.project_id}
            aria-describedby={errors.project_id ? 'project_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.project_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.project_id && (
            <div
              id="project_id-error"
              role="alert"
              data-testid="stories-field-project_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.project_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="sprint_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Sprint Id *
          </label>
          <input
            type="text"
            id="sprint_id"
            data-testid="stories-field-sprint_id"
            value={(formData.sprint_id as string) || ''}
            onChange={(e) => handleChange('sprint_id', e.target.value)}
            aria-invalid={!!errors.sprint_id}
            aria-describedby={errors.sprint_id ? 'sprint_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.sprint_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.sprint_id && (
            <div
              id="sprint_id-error"
              role="alert"
              data-testid="stories-field-sprint_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.sprint_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="type"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Type *
          </label>
          <input
            type="text"
            id="type"
            data-testid="stories-field-type"
            value={(formData.type as string) || ''}
            onChange={(e) => handleChange('type', e.target.value)}
            aria-invalid={!!errors.type}
            aria-describedby={errors.type ? 'type-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.type ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.type && (
            <div
              id="type-error"
              role="alert"
              data-testid="stories-field-type-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.type}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="priority"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Priority *
          </label>
          <input
            type="text"
            id="priority"
            data-testid="stories-field-priority"
            value={(formData.priority as string) || ''}
            onChange={(e) => handleChange('priority', e.target.value)}
            aria-invalid={!!errors.priority}
            aria-describedby={errors.priority ? 'priority-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.priority ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.priority && (
            <div
              id="priority-error"
              role="alert"
              data-testid="stories-field-priority-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.priority}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="story_points"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Story Points *
          </label>
          <input
            type="number"
            id="story_points"
            data-testid="stories-field-story_points"
            value={(formData.story_points as number) || 0}
            onChange={(e) => handleChange('story_points', Number(e.target.value))}
            aria-invalid={!!errors.story_points}
            aria-describedby={errors.story_points ? 'story_points-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.story_points ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.story_points && (
            <div
              id="story_points-error"
              role="alert"
              data-testid="stories-field-story_points-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.story_points}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="status"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Status *
          </label>
          <input
            type="text"
            id="status"
            data-testid="stories-field-status"
            value={(formData.status as string) || ''}
            onChange={(e) => handleChange('status', e.target.value)}
            aria-invalid={!!errors.status}
            aria-describedby={errors.status ? 'status-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.status ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.status && (
            <div
              id="status-error"
              role="alert"
              data-testid="stories-field-status-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.status}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="acceptance_criteria"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Acceptance Criteria *
          </label>
          <textarea
            id="acceptance_criteria"
            data-testid="stories-field-acceptance_criteria"
            value={(formData.acceptance_criteria as string) || ''}
            onChange={(e) => handleChange('acceptance_criteria', e.target.value)}
            aria-invalid={!!errors.acceptance_criteria}
            aria-describedby={errors.acceptance_criteria ? 'acceptance_criteria-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.acceptance_criteria ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.acceptance_criteria && (
            <div
              id="acceptance_criteria-error"
              role="alert"
              data-testid="stories-field-acceptance_criteria-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.acceptance_criteria}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="assigned_to"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Assigned To *
          </label>
          <input
            type="text"
            id="assigned_to"
            data-testid="stories-field-assigned_to"
            value={(formData.assigned_to as string) || ''}
            onChange={(e) => handleChange('assigned_to', e.target.value)}
            aria-invalid={!!errors.assigned_to}
            aria-describedby={errors.assigned_to ? 'assigned_to-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.assigned_to ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.assigned_to && (
            <div
              id="assigned_to-error"
              role="alert"
              data-testid="stories-field-assigned_to-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.assigned_to}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="ado_work_item_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Ado Work Item Id *
          </label>
          <input
            type="number"
            id="ado_work_item_id"
            data-testid="stories-field-ado_work_item_id"
            value={(formData.ado_work_item_id as number) || 0}
            onChange={(e) => handleChange('ado_work_item_id', Number(e.target.value))}
            aria-invalid={!!errors.ado_work_item_id}
            aria-describedby={errors.ado_work_item_id ? 'ado_work_item_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.ado_work_item_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.ado_work_item_id && (
            <div
              id="ado_work_item_id-error"
              role="alert"
              data-testid="stories-field-ado_work_item_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.ado_work_item_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="stories-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="stories-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="stories-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t.cancel}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="stories-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t.submitting : t.submit}
        </button>
      </div>
    </form>
  );
};

