/**
 * EvidenceCorrelationCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L30 (evidence_correlation)
 * Generated: 2026-03-12T09:00:54Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new evidence_correlation records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createEvidenceCorrelationRecord } from '@api/evidence_correlationApi';
import type { EvidenceCorrelationRecord, CreateEvidenceCorrelationRecordInput } from '@/types/evidence_correlation';

interface EvidenceCorrelationCreateFormProps {
  onSuccess: (record: EvidenceCorrelationRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const EvidenceCorrelationCreateForm: React.FC<EvidenceCorrelationCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('evidence_correlation.create_form');

  const [formData, setFormData] = useState<Partial<CreateEvidenceCorrelationRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createEvidenceCorrelationRecord(formData as CreateEvidenceCorrelationRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="evidence_correlation-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="evidence_correlation-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="evidence_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Evidence Id *
          </label>
          <input
            type="text"
            id="evidence_id"
            data-testid="evidence_correlation-field-evidence_id"
            value={(formData.evidence_id as string) || ''}
            onChange={(e) => handleChange('evidence_id', e.target.value)}
            aria-invalid={!!errors.evidence_id}
            aria-describedby={errors.evidence_id ? 'evidence_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.evidence_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.evidence_id && (
            <div
              id="evidence_id-error"
              role="alert"
              data-testid="evidence_correlation-field-evidence_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.evidence_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="correlation_type"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Correlation Type *
          </label>
          <input
            type="text"
            id="correlation_type"
            data-testid="evidence_correlation-field-correlation_type"
            value={(formData.correlation_type as string) || ''}
            onChange={(e) => handleChange('correlation_type', e.target.value)}
            aria-invalid={!!errors.correlation_type}
            aria-describedby={errors.correlation_type ? 'correlation_type-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.correlation_type ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.correlation_type && (
            <div
              id="correlation_type-error"
              role="alert"
              data-testid="evidence_correlation-field-correlation_type-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.correlation_type}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="related_evidence_ids"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Related Evidence Ids *
          </label>
          <textarea
            id="related_evidence_ids"
            data-testid="evidence_correlation-field-related_evidence_ids"
            value={(formData.related_evidence_ids as string) || ''}
            onChange={(e) => handleChange('related_evidence_ids', e.target.value)}
            aria-invalid={!!errors.related_evidence_ids}
            aria-describedby={errors.related_evidence_ids ? 'related_evidence_ids-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.related_evidence_ids ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.related_evidence_ids && (
            <div
              id="related_evidence_ids-error"
              role="alert"
              data-testid="evidence_correlation-field-related_evidence_ids-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.related_evidence_ids}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="correlation_strength"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Correlation Strength *
          </label>
          <input
            type="text"
            id="correlation_strength"
            data-testid="evidence_correlation-field-correlation_strength"
            value={(formData.correlation_strength as string) || ''}
            onChange={(e) => handleChange('correlation_strength', e.target.value)}
            aria-invalid={!!errors.correlation_strength}
            aria-describedby={errors.correlation_strength ? 'correlation_strength-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.correlation_strength ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.correlation_strength && (
            <div
              id="correlation_strength-error"
              role="alert"
              data-testid="evidence_correlation-field-correlation_strength-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.correlation_strength}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="confidence_percent"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Confidence Percent *
          </label>
          <input
            type="number"
            id="confidence_percent"
            data-testid="evidence_correlation-field-confidence_percent"
            value={(formData.confidence_percent as number) || 0}
            onChange={(e) => handleChange('confidence_percent', Number(e.target.value))}
            aria-invalid={!!errors.confidence_percent}
            aria-describedby={errors.confidence_percent ? 'confidence_percent-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.confidence_percent ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.confidence_percent && (
            <div
              id="confidence_percent-error"
              role="alert"
              data-testid="evidence_correlation-field-confidence_percent-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.confidence_percent}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="evidence_correlation-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="evidence_correlation-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="evidence_correlation-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="evidence_correlation-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

