/**
 * ProjectsDetailDrawer -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L1 (projects)
 * Generated: 2026-03-11T18:59:02Z
 * Generator: screens-machine-v1.0.0
 * 
 * Slide-in drawer showing full record details with focus trap and keyboard navigation.
 * Based on: Project 31 (EVA Faces) portal-face/WIDetailDrawer pattern
 * 
 * Accessibility:
 * - role=dialog, aria-modal=true
 * - Focus trap (auto-focus close button on open)
 * - Escape key closes drawer
 * - Backdrop click closes drawer
 * - WCAG 2.1 Level AA compliant
 */

import React, { useEffect, useRef } from 'react';
import type { ProjectsRecord } from '@/types/projects';
import { useLang } from '@context/LangContext';

interface ProjectsDetailDrawerProps {
  record: ProjectsRecord | null;
  onClose: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';

export const ProjectsDetailDrawer: React.FC<ProjectsDetailDrawerProps> = ({ record, onClose }) => {
  const { lang } = useLang();
  const closeRef = useRef<HTMLButtonElement>(null);

  // Auto-focus close button when drawer opens
  useEffect(() => {
    if (record) closeRef.current?.focus();
  }, [record]);

  // Escape key closes drawer
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  if (!record) return null;

  const t = {
    close:     lang === 'fr' ? 'Fermer' : 'Close',
    details:   lang === 'fr' ? 'Détails' : 'Details',
    metadata:  lang === 'fr' ? 'Métadonnées' : 'Metadata',
    layer:     lang === 'fr' ? 'Couche' : 'Layer',
    id:        lang === 'fr' ? 'Identifiant' : 'ID',
  };

  return (
    <>
      {/* Backdrop */}
      <div
        data-testid="projects-drawer-backdrop"
        aria-hidden="true"
        onClick={onClose}
        style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(0, 0, 0, 0.35)',
          zIndex: 200,
        }}
      />

      {/* Drawer panel */}
      <div
        data-testid="projects-drawer"
        role="dialog"
        aria-modal="true"
        aria-label={`${t.details}: ${record.id}`}
        style={{
          position: 'fixed',
          top: 0,
          right: 0,
          bottom: 0,
          width: Math.min(480, window.innerWidth),
          background: '#fff',
          boxShadow: '-4px 0 16px rgba(0, 0, 0, 0.15)',
          zIndex: 201,
          overflowY: 'auto',
          padding: '24px 24px 32px',
          display: 'flex',
          flexDirection: 'column',
          gap: 16,
          fontFamily: 'Noto Sans, sans-serif',
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <span style={{ fontSize: '0.75rem', fontWeight: 700, color: GC_MUTED }}>
              L1 - projects
            </span>
            <h2 data-testid="projects-drawer-title" style={{ margin: '4px 0 0', fontSize: '1rem', color: GC_TEXT }}>
              {record.id}
            </h2>
          </div>
          <button
            ref={closeRef}
            onClick={onClose}
            aria-label={t.close}
            data-testid="projects-drawer-close"
            style={{
              background: 'none',
              border: 'none',
              fontSize: '1.4rem',
              cursor: 'pointer',
              lineHeight: 1,
              padding: 4,
              color: GC_MUTED,
            }}
          >
            ×
          </button>
        </div>

        {/* Metadata section */}
        <section style={{ paddingBottom: 16, borderBottom: `1px solid ${GC_BORDER}` }}>
          <h3 style={{ fontSize: '0.8rem', fontWeight: 700, marginBottom: 8, color: GC_MUTED }}>
            {t.metadata}
          </h3>
          <dl style={{ margin: 0, display: 'grid', gridTemplateColumns: '120px 1fr', gap: '8px 12px', fontSize: '0.875rem' }}>
            <dt style={{ color: GC_MUTED, fontWeight: 600 }}>{t.layer}:</dt>
            <dd style={{ margin: 0, color: GC_TEXT }}>L1</dd>
            
            <dt style={{ color: GC_MUTED, fontWeight: 600 }}>{t.id}:</dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-all' }}>
              {record.id}
            </dd>
          </dl>
        </section>

        {/* Field sections (auto-generated from schema) */}
        <section>
          <h3 style={{ fontSize: '0.8rem', fontWeight: 700, marginBottom: 8, color: GC_MUTED }}>
            Record Details
          </h3>
                    <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Phase
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.phase ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Goal
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.goal ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              PBI Total
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.pbi_total ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Maturity
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.maturity ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Sprint Context
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.sprint_context ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Label Fr
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.label_fr ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              ADO Epic ID
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.ado_epic_id ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              ADO Project
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.ado_project ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Folder
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.folder ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Notes
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.notes ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Depends On
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.depends_on ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Status
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.status ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Github Repo
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.github_repo ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Category
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.category ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              PBI Done
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.pbi_done ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Label
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.label ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              WBS ID
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.wbs_id ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Blocked By
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.blocked_by ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Services
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.services ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Is Active
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.is_active ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Modified By
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.modified_by ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Modified At
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.modified_at ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Created By
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.created_by ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Created At
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.created_at ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Row Version
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.row_version ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Source File
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.source_file ?? 'N/A')}
            </dd>
          </dl>

          <dl>
            <dt style={{ fontSize: '0.75rem', fontWeight: 600, color: GC_MUTED, marginBottom: 4 }}>
              Layer
            </dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-word' }}>
              {String(record.layer ?? 'N/A')}
            </dd>
          </dl>
        </section>

        {/* TODO: Add actions (Edit, Delete, etc.) */}
        <div style={{ marginTop: 'auto', paddingTop: 16, borderTop: `1px solid ${GC_BORDER}` }}>
          <button
            onClick={onClose}
            style={{
              width: '100%',
              padding: '10px 16px',
              background: GC_BLUE,
              color: '#fff',
              border: 'none',
              borderRadius: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              cursor: 'pointer',
            }}
          >
            {t.close}
          </button>
        </div>
      </div>
    </>
  );
};

