/**
 * ProjectsDetailDrawer -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L25 (projects)
 * Generated: 2026-03-11T00:49:10Z
 * Generator: screens-machine-v2.0.0
 * 
 * Slide-in drawer showing full record details with focus trap and keyboard navigation.
 * Based on: Project 31 (EVA Faces) portal-face/WIDetailDrawer pattern
 * 
 * Accessibility:
 * - role=dialog, aria-modal=true
 * - Focus trap (auto-focus close button on open)
 * - Escape key closes drawer
 * - Backdrop click closes drawer
 * - WCAG 2.1 Level AA compliant
 */

import React, { useEffect, useRef } from 'react';
import type { ProjectsRecord } from '@/types/projects';
import { useLang } from '@context/LangContext';

interface ProjectsDetailDrawerProps {
  record: ProjectsRecord | null;
  onClose: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';

export const ProjectsDetailDrawer: React.FC<ProjectsDetailDrawerProps> = ({ record, onClose }) => {
  const { lang } = useLang();
  const closeRef = useRef<HTMLButtonElement>(null);

  // Auto-focus close button when drawer opens
  useEffect(() => {
    if (record) closeRef.current?.focus();
  }, [record]);

  // Escape key closes drawer
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  if (!record) return null;

  const t = {
    close:     lang === 'fr' ? 'Fermer' : 'Close',
    details:   lang === 'fr' ? 'Détails' : 'Details',
    metadata:  lang === 'fr' ? 'Métadonnées' : 'Metadata',
    layer:     lang === 'fr' ? 'Couche' : 'Layer',
    id:        lang === 'fr' ? 'Identifiant' : 'ID',
  };

  return (
    <>
      {/* Backdrop */}
      <div
        data-testid="projects-drawer-backdrop"
        aria-hidden="true"
        onClick={onClose}
        style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(0, 0, 0, 0.35)',
          zIndex: 200,
        }}
      />

      {/* Drawer panel */}
      <div
        data-testid="projects-drawer"
        role="dialog"
        aria-modal="true"
        aria-label={`${t.details}: ${record.id}`}
        style={{
          position: 'fixed',
          top: 0,
          right: 0,
          bottom: 0,
          width: Math.min(480, window.innerWidth),
          background: '#fff',
          boxShadow: '-4px 0 16px rgba(0, 0, 0, 0.15)',
          zIndex: 201,
          overflowY: 'auto',
          padding: '24px 24px 32px',
          display: 'flex',
          flexDirection: 'column',
          gap: 16,
          fontFamily: 'Noto Sans, sans-serif',
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <span style={{ fontSize: '0.75rem', fontWeight: 700, color: GC_MUTED }}>
              L25 - projects
            </span>
            <h2 data-testid="projects-drawer-title" style={{ margin: '4px 0 0', fontSize: '1rem', color: GC_TEXT }}>
              {record.id}
            </h2>
          </div>
          <button
            ref={closeRef}
            onClick={onClose}
            aria-label={t.close}
            data-testid="projects-drawer-close"
            style={{
              background: 'none',
              border: 'none',
              fontSize: '1.4rem',
              cursor: 'pointer',
              lineHeight: 1,
              padding: 4,
              color: GC_MUTED,
            }}
          >
            ×
          </button>
        </div>

        {/* Metadata section */}
        <section style={{ paddingBottom: 16, borderBottom: `1px solid ${GC_BORDER}` }}>
          <h3 style={{ fontSize: '0.8rem', fontWeight: 700, marginBottom: 8, color: GC_MUTED }}>
            {t.metadata}
          </h3>
          <dl style={{ margin: 0, display: 'grid', gridTemplateColumns: '120px 1fr', gap: '8px 12px', fontSize: '0.875rem' }}>
            <dt style={{ color: GC_MUTED, fontWeight: 600 }}>{t.layer}:</dt>
            <dd style={{ margin: 0, color: GC_TEXT }}>L25</dd>
            
            <dt style={{ color: GC_MUTED, fontWeight: 600 }}>{t.id}:</dt>
            <dd style={{ margin: 0, color: GC_TEXT, wordBreak: 'break-all' }}>
              {record.id}
            </dd>
          </dl>
        </section>

        {/* Field sections (auto-generated from schema) */}
        <section>
          <h3 style={{ fontSize: '0.8rem', fontWeight: 700, marginBottom: 8, color: GC_MUTED }}>
            Record Details
          </h3>
                      <dl style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Id:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.id !== null && record.id !== undefined 
                      ? String(record.id) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Phase:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.phase !== null && record.phase !== undefined 
                      ? String(record.phase) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Goal:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.goal !== null && record.goal !== undefined 
                      ? String(record.goal) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Pbi Total:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.pbi_total !== null && record.pbi_total !== undefined 
                      ? String(record.pbi_total) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Maturity:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.maturity !== null && record.maturity !== undefined 
                      ? String(record.maturity) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Sprint Context:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.sprint_context !== null && record.sprint_context !== undefined 
                      ? String(record.sprint_context) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Label Fr:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.label_fr !== null && record.label_fr !== undefined 
                      ? String(record.label_fr) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Ado Epic Id:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.ado_epic_id !== null && record.ado_epic_id !== undefined 
                      ? String(record.ado_epic_id) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Ado Project:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.ado_project !== null && record.ado_project !== undefined 
                      ? String(record.ado_project) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Folder:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.folder !== null && record.folder !== undefined 
                      ? String(record.folder) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Notes:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.notes !== null && record.notes !== undefined 
                      ? String(record.notes) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Depends On:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.depends_on !== null && record.depends_on !== undefined 
                      ? String(record.depends_on) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Status:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.status !== null && record.status !== undefined 
                      ? String(record.status) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Github Repo:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.github_repo !== null && record.github_repo !== undefined 
                      ? String(record.github_repo) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Category:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.category !== null && record.category !== undefined 
                      ? String(record.category) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Pbi Done:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.pbi_done !== null && record.pbi_done !== undefined 
                      ? String(record.pbi_done) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Label:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.label !== null && record.label !== undefined 
                      ? String(record.label) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Wbs Id:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.wbs_id !== null && record.wbs_id !== undefined 
                      ? String(record.wbs_id) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Blocked By:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.blocked_by !== null && record.blocked_by !== undefined 
                      ? String(record.blocked_by) 
                      : '—'}
                  </dd>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', gap: 12, padding: '8px 0' }}>
                  <dt style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT }}>
                    Services:
                  </dt>
                  <dd style={{ fontSize: '0.875rem', color: GC_TEXT, margin: 0 }}>
                    {record.services !== null && record.services !== undefined 
                      ? String(record.services) 
                      : '—'}
                  </dd>
                </div>
            </dl>
        </section>

        {/* TODO: Add actions (Edit, Delete, etc.) */}
        <div style={{ marginTop: 'auto', paddingTop: 16, borderTop: `1px solid ${GC_BORDER}` }}>
          <button
            onClick={onClose}
            style={{
              width: '100%',
              padding: '10px 16px',
              background: GC_BLUE,
              color: '#fff',
              border: 'none',
              borderRadius: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              cursor: 'pointer',
            }}
          >
            {t.close}
          </button>
        </div>
      </div>
    </>
  );
};

