/**
 * ProjectWorkCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L78 (project_work)
 * Generated: 2026-03-12T09:01:27Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new project_work records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createProjectWorkRecord } from '@api/project_workApi';
import type { ProjectWorkRecord, CreateProjectWorkRecordInput } from '@/types/project_work';

interface ProjectWorkCreateFormProps {
  onSuccess: (record: ProjectWorkRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const ProjectWorkCreateForm: React.FC<ProjectWorkCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('project_work.create_form');

  const [formData, setFormData] = useState<Partial<CreateProjectWorkRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createProjectWorkRecord(formData as CreateProjectWorkRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="project_work-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="project_work-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="project_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Project Id *
          </label>
          <input
            type="text"
            id="project_id"
            data-testid="project_work-field-project_id"
            value={(formData.project_id as string) || ''}
            onChange={(e) => handleChange('project_id', e.target.value)}
            aria-invalid={!!errors.project_id}
            aria-describedby={errors.project_id ? 'project_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.project_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.project_id && (
            <div
              id="project_id-error"
              role="alert"
              data-testid="project_work-field-project_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.project_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="current_phase"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Current Phase *
          </label>
          <input
            type="text"
            id="current_phase"
            data-testid="project_work-field-current_phase"
            value={(formData.current_phase as string) || ''}
            onChange={(e) => handleChange('current_phase', e.target.value)}
            aria-invalid={!!errors.current_phase}
            aria-describedby={errors.current_phase ? 'current_phase-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.current_phase ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.current_phase && (
            <div
              id="current_phase-error"
              role="alert"
              data-testid="project_work-field-current_phase-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.current_phase}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="session_summary"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Session Summary *
          </label>
          <textarea
            id="session_summary"
            data-testid="project_work-field-session_summary"
            value={(formData.session_summary as string) || ''}
            onChange={(e) => handleChange('session_summary', e.target.value)}
            aria-invalid={!!errors.session_summary}
            aria-describedby={errors.session_summary ? 'session_summary-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.session_summary ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.session_summary && (
            <div
              id="session_summary-error"
              role="alert"
              data-testid="project_work-field-session_summary-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.session_summary}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="tasks"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Tasks
          </label>
          <textarea
            id="tasks"
            data-testid="project_work-field-tasks"
            value={(formData.tasks as string) || ''}
            onChange={(e) => handleChange('tasks', e.target.value)}
            aria-invalid={!!errors.tasks}
            aria-describedby={errors.tasks ? 'tasks-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.tasks ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.tasks && (
            <div
              id="tasks-error"
              role="alert"
              data-testid="project_work-field-tasks-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.tasks}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="blockers"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Blockers
          </label>
          <textarea
            id="blockers"
            data-testid="project_work-field-blockers"
            value={(formData.blockers as string) || ''}
            onChange={(e) => handleChange('blockers', e.target.value)}
            aria-invalid={!!errors.blockers}
            aria-describedby={errors.blockers ? 'blockers-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.blockers ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.blockers && (
            <div
              id="blockers-error"
              role="alert"
              data-testid="project_work-field-blockers-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.blockers}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="metrics"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Metrics *
          </label>
          <textarea
            id="metrics"
            data-testid="project_work-field-metrics"
            value={(formData.metrics as string) || ''}
            onChange={(e) => handleChange('metrics', e.target.value)}
            aria-invalid={!!errors.metrics}
            aria-describedby={errors.metrics ? 'metrics-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.metrics ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.metrics && (
            <div
              id="metrics-error"
              role="alert"
              data-testid="project_work-field-metrics-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.metrics}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="next_steps"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Next Steps
          </label>
          <textarea
            id="next_steps"
            data-testid="project_work-field-next_steps"
            value={(formData.next_steps as string) || ''}
            onChange={(e) => handleChange('next_steps', e.target.value)}
            aria-invalid={!!errors.next_steps}
            aria-describedby={errors.next_steps ? 'next_steps-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.next_steps ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.next_steps && (
            <div
              id="next_steps-error"
              role="alert"
              data-testid="project_work-field-next_steps-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.next_steps}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="project_work-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="project_work-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="project_work-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="project_work-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

