/**
 * {{LAYER_TITLE}}EditForm -- Auto-generated by Screens Machine v2.0.0
 * 
 * Data Model Layer: {{LAYER_ID}} ({{LAYER_NAME}})
 * Generated: {{TIMESTAMP}}
 * Generator: {{GENERATOR}}
 * 
 * Form for editing existing {{LAYER_NAME}} records with validation and error handling.
 * 
 * Features:
 * - Pre-populated with existing values
 * - Client-side validation
 * - Field-level error messages
 * - Update/Cancel actions
 * - Accessible form markup
 * - WCAG 2.1 Level AA compliant
 * 
 * Session 46 Enhancements:
 * - GC Design System tokens (centralized)
 * - 6-language i18n support (EN/FR/ES/DE/PT/CN)
 * - EVA Fluent UI components for form fields
 */

import React, { useState, useEffect } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { update{{LAYER_TITLE}}Record } from '@api/{{LAYER_NAME}}Api';
import type { {{ENTITY_TYPE}}, Update{{ENTITY_TYPE}}Input } from '@/types/{{LAYER_NAME}}';
import { GC_TEXT, GC_MUTED, GC_BORDER, GC_SURFACE, GC_BLUE, GC_ERROR, GC_SUCCESS } from '@styles/tokens';

interface {{LAYER_TITLE}}EditFormProps {
  record: {{ENTITY_TYPE}};
  onSuccess: (record: {{ENTITY_TYPE}}) => void;
  onCancel: () => void;
}

export const {{LAYER_TITLE}}EditForm: React.FC<{{LAYER_TITLE}}EditFormProps> = ({ record, onSuccess, onCancel }) => {
  const t = useLiterals('{{LAYER_NAME}}.edit_form');

  const [formData, setFormData] = useState<Partial<Update{{ENTITY_TYPE}}Input>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  // Initialize form data with existing record values
  useEffect(() => {
    const initial: Partial<Update{{ENTITY_TYPE}}Input> = {};
    // TODO: Initialize form fields from record
    setFormData(initial);
  }, [record]);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const hasChanges = (): boolean => {
    // TODO: Check if form data differs from original record
    return false;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!hasChanges()) {
      setSubmitError(t.noChanges);
      return;
    }

    if (!validate()) return;

    setSubmitting(true);
    try {
      const updated = await update{{LAYER_TITLE}}Record(
        record.{{PK_FIELD}},
        formData as Update{{ENTITY_TYPE}}Input
      );
      onSuccess(updated);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="{{LAYER_NAME}}-edit-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <div style={{ marginBottom: 24 }}>
        <h2 style={{ margin: '0 0 4px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
          {t.title}
        </h2>
        <p style={{ margin: 0, fontSize: '0.75rem', color: GC_MUTED }}>
          {{LAYER_ID}}: {record.{{PK_FIELD}}}
        </p>
      </div>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="{{LAYER_NAME}}-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t.error}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
        {/* TODO: Add dynamic form fields based on schema */}
        <p style={{ fontSize: '0.875rem', color: GC_MUTED }}>
          Form fields will be generated based on layer schema
        </p>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="{{LAYER_NAME}}-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t.cancel}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="{{LAYER_NAME}}-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t.submitting : t.submit}
        </button>
      </div>
    </form>
  );
};
