/**
 * {{LAYER_TITLE}}GraphView -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: {{LAYER_ID}} ({{LAYER_NAME}})
 * Generated: {{TIMESTAMP}}
 * Generator: {{GENERATOR}}
 * 
 * Data visualization component for {{LAYER_NAME}} records.
 * Placeholder for charts, graphs, network diagrams, or other visualizations.
 * 
 * Recommended libraries:
 * - Recharts (declarative React charts)
 * - D3.js (flexible custom visualizations)
 * - Visx (low-level visualization primitives)
 * - React Flow (node-based diagrams)
 * 
 * Accessibility:
 * - Provide text alternatives for charts (data tables)
 * - Keyboard navigation for interactive elements
 * - ARIA labels for chart regions
 * - Color contrast for all visual elements
 */

import React, { useMemo } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import type { {{ENTITY_TYPE}} } from '@/types/{{LAYER_NAME}}';

interface {{LAYER_TITLE}}GraphViewProps {
  records: {{ENTITY_TYPE}}[];
  visualizationType?: 'bar' | 'line' | 'pie' | 'network' | 'timeline';
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const CHART_COLORS = [
  '#1d70b8', // GC Blue
  '#00703c', // Success green
  '#912b88', // Purple
  '#d4351c', // Error red
  '#f47738', // Orange
];

export const {{LAYER_TITLE}}GraphView: React.FC<{{LAYER_TITLE}}GraphViewProps> = ({
  records,
  visualizationType = 'bar',
}) => {
  const t = useLiterals('{{LAYER_NAME}}.graph_view');
  const { lang } = useLang();

  const t = {
    title:          lang === 'fr' ? 'Visualisation' : 'Visualization',
    noData:         lang === 'fr' ? 'Aucune donnée à afficher' : 'No data to display',
    recordCount:    lang === 'fr' ? 'Enregistrements' : 'Records',
    comingSoon:     lang === 'fr' ? 'Prochainement disponible' : 'Coming soon',
    placeholderMsg: lang === 'fr' 
      ? 'Cette visualisation sera implémentée en fonction des besoins spécifiques de la couche.'
      : 'This visualization will be implemented based on layer-specific requirements.',
  };

  // Compute simple stats for demonstration
  const stats = useMemo(() => {
    return {
      total: records.length,
      // TODO: Add layer-specific aggregations
    };
  }, [records]);

  if (records.length === 0) {
    return (
      <div
        data-testid="{{LAYER_NAME}}-graph-empty"
        style={{
          padding: '48px 24px',
          textAlign: 'center',
          background: GC_SURFACE,
          border: `1px solid ${GC_BORDER}`,
          borderRadius: 4,
          fontFamily: 'Noto Sans, sans-serif',
        }}
      >
        <p style={{ fontSize: '0.875rem', color: GC_MUTED }}>{t.noData}</p>
      </div>
    );
  }

  return (
    <div
      data-testid="{{LAYER_NAME}}-graph"
      style={{
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Header */}
      <div style={{ marginBottom: 20 }}>
        <h3 style={{ margin: '0 0 4px', fontSize: '1rem', fontWeight: 700, color: GC_TEXT }}>
          {t.title}: {{LAYER_TITLE}}
        </h3>
        <p style={{ margin: 0, fontSize: '0.75rem', color: GC_MUTED }}>
          {stats.total} {t.recordCount} | {visualizationType} chart
        </p>
      </div>

      {/* Placeholder visualization area */}
      <div
        role="region"
        aria-label={`${t.title} - ${visualizationType}`}
        style={{
          minHeight: 300,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          background: GC_SURFACE,
          border: `2px dashed ${GC_BORDER}`,
          borderRadius: 4,
          padding: '40px 24px',
        }}
      >
        <svg
          width="80"
          height="80"
          viewBox="0 0 24 24"
          fill="none"
          stroke={GC_MUTED}
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          style={{ marginBottom: 16 }}
        >
          <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
          <line x1="3" y1="9" x2="21" y2="9" />
          <line x1="9" y1="21" x2="9" y2="9" />
        </svg>
        <p style={{ fontSize: '0.875rem', fontWeight: 600, color: GC_TEXT, marginBottom: 4 }}>
          {t.comingSoon}
        </p>
        <p style={{ fontSize: '0.75rem', color: GC_MUTED, textAlign: 'center', maxWidth: 400 }}>
          {t.placeholderMsg}
        </p>
      </div>

      {/* Stats summary */}
      <div
        style={{
          marginTop: 20,
          padding: 16,
          background: GC_SURFACE,
          borderRadius: 4,
        }}
      >
        <h4 style={{ margin: '0 0 12px', fontSize: '0.875rem', fontWeight: 700, color: GC_TEXT }}>
          {lang === 'fr' ? 'Statistiques' : 'Statistics'}
        </h4>
        <dl style={{ margin: 0, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '12px', fontSize: '0.875rem' }}>
          <div>
            <dt style={{ color: GC_MUTED, fontSize: '0.75rem', marginBottom: 2 }}>{t.recordCount}:</dt>
            <dd data-testid="{{LAYER_NAME}}-stat-total" style={{ margin: 0, fontSize: '1.25rem', fontWeight: 700, color: GC_BLUE }}>
              {stats.total}
            </dd>
          </div>
          {/* TODO: Add layer-specific stats */}
        </dl>
      </div>

      {/* Data table (accessibility alternative to chart) */}
      <details style={{ marginTop: 20 }}>
        <summary
          style={{
            padding: '8px 12px',
            background: GC_SURFACE,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            cursor: 'pointer',
            fontSize: '0.875rem',
            fontWeight: 600,
            color: GC_TEXT,
          }}
        >
          {lang === 'fr' ? 'Voir les données tabulaires' : 'View data table'}
        </summary>
        <div style={{ marginTop: 12, overflowX: 'auto' }}>
          <table
            data-testid="{{LAYER_NAME}}-data-table"
            style={{
              width: '100%',
              borderCollapse: 'collapse',
              fontSize: '0.75rem',
            }}
          >
            <thead>
              <tr style={{ background: GC_SURFACE, borderBottom: `2px solid ${GC_BORDER}` }}>
                <th style={{ padding: '8px 12px', textAlign: 'left', fontWeight: 600 }}>{{PK_FIELD}}</th>
                {/* TODO: Add other column headers based on schema */}
              </tr>
            </thead>
            <tbody>
              {records.slice(0, 10).map((record, idx) => (
                <tr key={record.{{PK_FIELD}}} style={{ borderBottom: `1px solid ${GC_BORDER}` }}>
                  <td style={{ padding: '8px 12px' }}>{record.{{PK_FIELD}}}</td>
                  {/* TODO: Add other cells based on schema */}
                </tr>
              ))}
            </tbody>
          </table>
          {records.length > 10 && (
            <p style={{ fontSize: '0.75rem', color: GC_MUTED, marginTop: 8, textAlign: 'center' }}>
              {lang === 'fr' 
                ? `Affichage de 10 sur ${records.length} enregistrements`
                : `Showing 10 of ${records.length} records`}
            </p>
          )}
        </div>
      </details>
    </div>
  );
};
