/**
 * QualityGateCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L34 (quality_gates)
 * Generated: 2026-03-11T15:12:21Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new quality_gates records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createQualityGateRecord } from '@api/quality_gatesApi';
import type { QualityGateRecord, CreateQualityGateRecordInput } from '@/types/quality_gates';

interface QualityGateCreateFormProps {
  onSuccess: (record: QualityGateRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const QualityGateCreateForm: React.FC<QualityGateCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('quality_gates.create_form');

  const [formData, setFormData] = useState<Partial<CreateQualityGateRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
        if (!formData.is_active) {
      newErrors.is_active = t('errors.required');
    }
    if (!formData.label) {
      newErrors.label = t('errors.required');
    }
    if (!formData.project_id) {
      newErrors.project_id = t('errors.required');
    }
    if (!formData.mti_threshold) {
      newErrors.mti_threshold = t('errors.required');
    }
    if (!formData.test_coverage_percent) {
      newErrors.test_coverage_percent = t('errors.required');
    }
    if (!formData.gates_per_phase) {
      newErrors.gates_per_phase = t('errors.required');
    }
    if (!formData.blockers) {
      newErrors.blockers = t('errors.required');
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createQualityGateRecord(formData as CreateQualityGateRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="quality_gates-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="quality_gates-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="quality_gates-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="quality_gates-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="label"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Label *
          </label>
          <input
            type="text"
            id="label"
            data-testid="quality_gates-field-label"
            value={(formData.label as string) || ''}
            onChange={(e) => handleChange('label', e.target.value)}
            aria-invalid={!!errors.label}
            aria-describedby={errors.label ? 'label-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.label ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.label && (
            <div
              id="label-error"
              role="alert"
              data-testid="quality_gates-field-label-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.label}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="project_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Project Id *
          </label>
          <input
            type="text"
            id="project_id"
            data-testid="quality_gates-field-project_id"
            value={(formData.project_id as string) || ''}
            onChange={(e) => handleChange('project_id', e.target.value)}
            aria-invalid={!!errors.project_id}
            aria-describedby={errors.project_id ? 'project_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.project_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.project_id && (
            <div
              id="project_id-error"
              role="alert"
              data-testid="quality_gates-field-project_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.project_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="mti_threshold"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Mti Threshold *
          </label>
          <input
            type="number"
            id="mti_threshold"
            data-testid="quality_gates-field-mti_threshold"
            value={(formData.mti_threshold as number) || 0}
            onChange={(e) => handleChange('mti_threshold', Number(e.target.value))}
            aria-invalid={!!errors.mti_threshold}
            aria-describedby={errors.mti_threshold ? 'mti_threshold-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.mti_threshold ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.mti_threshold && (
            <div
              id="mti_threshold-error"
              role="alert"
              data-testid="quality_gates-field-mti_threshold-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.mti_threshold}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="test_coverage_percent"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Test Coverage Percent *
          </label>
          <input
            type="number"
            id="test_coverage_percent"
            data-testid="quality_gates-field-test_coverage_percent"
            value={(formData.test_coverage_percent as number) || 0}
            onChange={(e) => handleChange('test_coverage_percent', Number(e.target.value))}
            aria-invalid={!!errors.test_coverage_percent}
            aria-describedby={errors.test_coverage_percent ? 'test_coverage_percent-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.test_coverage_percent ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.test_coverage_percent && (
            <div
              id="test_coverage_percent-error"
              role="alert"
              data-testid="quality_gates-field-test_coverage_percent-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.test_coverage_percent}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="gates_per_phase"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Gates Per Phase *
          </label>
          <textarea
            id="gates_per_phase"
            data-testid="quality_gates-field-gates_per_phase"
            value={(formData.gates_per_phase as string) || ''}
            onChange={(e) => handleChange('gates_per_phase', e.target.value)}
            aria-invalid={!!errors.gates_per_phase}
            aria-describedby={errors.gates_per_phase ? 'gates_per_phase-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.gates_per_phase ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.gates_per_phase && (
            <div
              id="gates_per_phase-error"
              role="alert"
              data-testid="quality_gates-field-gates_per_phase-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.gates_per_phase}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="blockers"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Blockers *
          </label>
          <textarea
            id="blockers"
            data-testid="quality_gates-field-blockers"
            value={(formData.blockers as string) || ''}
            onChange={(e) => handleChange('blockers', e.target.value)}
            aria-invalid={!!errors.blockers}
            aria-describedby={errors.blockers ? 'blockers-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.blockers ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.blockers && (
            <div
              id="blockers-error"
              role="alert"
              data-testid="quality_gates-field-blockers-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.blockers}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="quality_gates-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="quality_gates-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

