/**
 * RuntimeConfigCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L18 (runtime_config)
 * Generated: 2026-03-12T09:00:46Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new runtime_config records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createRuntimeConfigRecord } from '@api/runtime_configApi';
import type { RuntimeConfigRecord, CreateRuntimeConfigRecordInput } from '@/types/runtime_config';

interface RuntimeConfigCreateFormProps {
  onSuccess: (record: RuntimeConfigRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const RuntimeConfigCreateForm: React.FC<RuntimeConfigCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('runtime_config.create_form');

  const [formData, setFormData] = useState<Partial<CreateRuntimeConfigRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createRuntimeConfigRecord(formData as CreateRuntimeConfigRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="runtime_config-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="runtime_config-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="config_def_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Config Def Id *
          </label>
          <input
            type="text"
            id="config_def_id"
            data-testid="runtime_config-field-config_def_id"
            value={(formData.config_def_id as string) || ''}
            onChange={(e) => handleChange('config_def_id', e.target.value)}
            aria-invalid={!!errors.config_def_id}
            aria-describedby={errors.config_def_id ? 'config_def_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.config_def_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.config_def_id && (
            <div
              id="config_def_id-error"
              role="alert"
              data-testid="runtime_config-field-config_def_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.config_def_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="environment"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Environment *
          </label>
          <input
            type="text"
            id="environment"
            data-testid="runtime_config-field-environment"
            value={(formData.environment as string) || ''}
            onChange={(e) => handleChange('environment', e.target.value)}
            aria-invalid={!!errors.environment}
            aria-describedby={errors.environment ? 'environment-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.environment ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.environment && (
            <div
              id="environment-error"
              role="alert"
              data-testid="runtime_config-field-environment-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.environment}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="service_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Service Id *
          </label>
          <input
            type="text"
            id="service_id"
            data-testid="runtime_config-field-service_id"
            value={(formData.service_id as string) || ''}
            onChange={(e) => handleChange('service_id', e.target.value)}
            aria-invalid={!!errors.service_id}
            aria-describedby={errors.service_id ? 'service_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.service_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.service_id && (
            <div
              id="service_id-error"
              role="alert"
              data-testid="runtime_config-field-service_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.service_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="value"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Value *
          </label>
          <input
            type="text"
            id="value"
            data-testid="runtime_config-field-value"
            value={(formData.value as string) || ''}
            onChange={(e) => handleChange('value', e.target.value)}
            aria-invalid={!!errors.value}
            aria-describedby={errors.value ? 'value-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.value ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.value && (
            <div
              id="value-error"
              role="alert"
              data-testid="runtime_config-field-value-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.value}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="updated_at"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Updated At *
          </label>
          <input
            type="datetime-local"
            id="updated_at"
            data-testid="runtime_config-field-updated_at"
            value={(formData.updated_at as string) || ''}
            onChange={(e) => handleChange('updated_at', e.target.value)}
            aria-invalid={!!errors.updated_at}
            aria-describedby={errors.updated_at ? 'updated_at-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.updated_at ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.updated_at && (
            <div
              id="updated_at-error"
              role="alert"
              data-testid="runtime_config-field-updated_at-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.updated_at}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="updated_by"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Updated By *
          </label>
          <input
            type="text"
            id="updated_by"
            data-testid="runtime_config-field-updated_by"
            value={(formData.updated_by as string) || ''}
            onChange={(e) => handleChange('updated_by', e.target.value)}
            aria-invalid={!!errors.updated_by}
            aria-describedby={errors.updated_by ? 'updated_by-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.updated_by ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.updated_by && (
            <div
              id="updated_by-error"
              role="alert"
              data-testid="runtime_config-field-updated_by-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.updated_by}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="runtime_config-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="runtime_config-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="runtime_config-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="runtime_config-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

