/**
 * InfrastructureDriftCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L86 (infrastructure_drift)
 * Generated: 2026-03-12T09:01:33Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new infrastructure_drift records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createInfrastructureDriftRecord } from '@api/infrastructure_driftApi';
import type { InfrastructureDriftRecord, CreateInfrastructureDriftRecordInput } from '@/types/infrastructure_drift';

interface InfrastructureDriftCreateFormProps {
  onSuccess: (record: InfrastructureDriftRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const InfrastructureDriftCreateForm: React.FC<InfrastructureDriftCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('infrastructure_drift.create_form');

  const [formData, setFormData] = useState<Partial<CreateInfrastructureDriftRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createInfrastructureDriftRecord(formData as CreateInfrastructureDriftRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="infrastructure_drift-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="infrastructure_drift-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="resource_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Resource Id *
          </label>
          <input
            type="text"
            id="resource_id"
            data-testid="infrastructure_drift-field-resource_id"
            value={(formData.resource_id as string) || ''}
            onChange={(e) => handleChange('resource_id', e.target.value)}
            aria-invalid={!!errors.resource_id}
            aria-describedby={errors.resource_id ? 'resource_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.resource_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.resource_id && (
            <div
              id="resource_id-error"
              role="alert"
              data-testid="infrastructure_drift-field-resource_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.resource_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="resource_type"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Resource Type *
          </label>
          <input
            type="text"
            id="resource_type"
            data-testid="infrastructure_drift-field-resource_type"
            value={(formData.resource_type as string) || ''}
            onChange={(e) => handleChange('resource_type', e.target.value)}
            aria-invalid={!!errors.resource_type}
            aria-describedby={errors.resource_type ? 'resource_type-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.resource_type ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.resource_type && (
            <div
              id="resource_type-error"
              role="alert"
              data-testid="infrastructure_drift-field-resource_type-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.resource_type}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="service"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Service *
          </label>
          <input
            type="text"
            id="service"
            data-testid="infrastructure_drift-field-service"
            value={(formData.service as string) || ''}
            onChange={(e) => handleChange('service', e.target.value)}
            aria-invalid={!!errors.service}
            aria-describedby={errors.service ? 'service-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.service ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.service && (
            <div
              id="service-error"
              role="alert"
              data-testid="infrastructure_drift-field-service-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.service}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="environment"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Environment *
          </label>
          <input
            type="text"
            id="environment"
            data-testid="infrastructure_drift-field-environment"
            value={(formData.environment as string) || ''}
            onChange={(e) => handleChange('environment', e.target.value)}
            aria-invalid={!!errors.environment}
            aria-describedby={errors.environment ? 'environment-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.environment ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.environment && (
            <div
              id="environment-error"
              role="alert"
              data-testid="infrastructure_drift-field-environment-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.environment}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="desired_state"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Desired State *
          </label>
          <textarea
            id="desired_state"
            data-testid="infrastructure_drift-field-desired_state"
            value={(formData.desired_state as string) || ''}
            onChange={(e) => handleChange('desired_state', e.target.value)}
            aria-invalid={!!errors.desired_state}
            aria-describedby={errors.desired_state ? 'desired_state-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.desired_state ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.desired_state && (
            <div
              id="desired_state-error"
              role="alert"
              data-testid="infrastructure_drift-field-desired_state-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.desired_state}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="actual_state"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Actual State *
          </label>
          <textarea
            id="actual_state"
            data-testid="infrastructure_drift-field-actual_state"
            value={(formData.actual_state as string) || ''}
            onChange={(e) => handleChange('actual_state', e.target.value)}
            aria-invalid={!!errors.actual_state}
            aria-describedby={errors.actual_state ? 'actual_state-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.actual_state ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.actual_state && (
            <div
              id="actual_state-error"
              role="alert"
              data-testid="infrastructure_drift-field-actual_state-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.actual_state}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="drift_detected"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Drift Detected *
          </label>
          <input
            type="checkbox"
            id="drift_detected"
            data-testid="infrastructure_drift-field-drift_detected"
            checked={(formData.drift_detected as boolean) || false}
            onChange={(e) => handleChange('drift_detected', e.target.checked)}
            aria-invalid={!!errors.drift_detected}
            aria-describedby={errors.drift_detected ? 'drift_detected-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.drift_detected && (
            <div
              id="drift_detected-error"
              role="alert"
              data-testid="infrastructure_drift-field-drift_detected-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.drift_detected}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="drift_severity"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Drift Severity *
          </label>
          <input
            type="text"
            id="drift_severity"
            data-testid="infrastructure_drift-field-drift_severity"
            value={(formData.drift_severity as string) || ''}
            onChange={(e) => handleChange('drift_severity', e.target.value)}
            aria-invalid={!!errors.drift_severity}
            aria-describedby={errors.drift_severity ? 'drift_severity-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.drift_severity ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.drift_severity && (
            <div
              id="drift_severity-error"
              role="alert"
              data-testid="infrastructure_drift-field-drift_severity-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.drift_severity}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="drift_fields"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Drift Fields *
          </label>
          <textarea
            id="drift_fields"
            data-testid="infrastructure_drift-field-drift_fields"
            value={(formData.drift_fields as string) || ''}
            onChange={(e) => handleChange('drift_fields', e.target.value)}
            aria-invalid={!!errors.drift_fields}
            aria-describedby={errors.drift_fields ? 'drift_fields-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.drift_fields ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.drift_fields && (
            <div
              id="drift_fields-error"
              role="alert"
              data-testid="infrastructure_drift-field-drift_fields-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.drift_fields}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="last_sync"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Last Sync *
          </label>
          <input
            type="datetime-local"
            id="last_sync"
            data-testid="infrastructure_drift-field-last_sync"
            value={(formData.last_sync as string) || ''}
            onChange={(e) => handleChange('last_sync', e.target.value)}
            aria-invalid={!!errors.last_sync}
            aria-describedby={errors.last_sync ? 'last_sync-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.last_sync ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.last_sync && (
            <div
              id="last_sync-error"
              role="alert"
              data-testid="infrastructure_drift-field-last_sync-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.last_sync}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="sync_status"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Sync Status *
          </label>
          <input
            type="text"
            id="sync_status"
            data-testid="infrastructure_drift-field-sync_status"
            value={(formData.sync_status as string) || ''}
            onChange={(e) => handleChange('sync_status', e.target.value)}
            aria-invalid={!!errors.sync_status}
            aria-describedby={errors.sync_status ? 'sync_status-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.sync_status ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.sync_status && (
            <div
              id="sync_status-error"
              role="alert"
              data-testid="infrastructure_drift-field-sync_status-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.sync_status}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="recommendation"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Recommendation *
          </label>
          <input
            type="text"
            id="recommendation"
            data-testid="infrastructure_drift-field-recommendation"
            value={(formData.recommendation as string) || ''}
            onChange={(e) => handleChange('recommendation', e.target.value)}
            aria-invalid={!!errors.recommendation}
            aria-describedby={errors.recommendation ? 'recommendation-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.recommendation ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.recommendation && (
            <div
              id="recommendation-error"
              role="alert"
              data-testid="infrastructure_drift-field-recommendation-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.recommendation}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="auto_remediate"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Auto Remediate *
          </label>
          <input
            type="checkbox"
            id="auto_remediate"
            data-testid="infrastructure_drift-field-auto_remediate"
            checked={(formData.auto_remediate as boolean) || false}
            onChange={(e) => handleChange('auto_remediate', e.target.checked)}
            aria-invalid={!!errors.auto_remediate}
            aria-describedby={errors.auto_remediate ? 'auto_remediate-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.auto_remediate && (
            <div
              id="auto_remediate-error"
              role="alert"
              data-testid="infrastructure_drift-field-auto_remediate-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.auto_remediate}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="manual_review_required"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Manual Review Required *
          </label>
          <input
            type="checkbox"
            id="manual_review_required"
            data-testid="infrastructure_drift-field-manual_review_required"
            checked={(formData.manual_review_required as boolean) || false}
            onChange={(e) => handleChange('manual_review_required', e.target.checked)}
            aria-invalid={!!errors.manual_review_required}
            aria-describedby={errors.manual_review_required ? 'manual_review_required-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.manual_review_required && (
            <div
              id="manual_review_required-error"
              role="alert"
              data-testid="infrastructure_drift-field-manual_review_required-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.manual_review_required}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="infrastructure_drift-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="infrastructure_drift-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="infrastructure_drift-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="infrastructure_drift-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

