/**
 * WorkStepEventsCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L89 (work_step_events)
 * Generated: 2026-03-12T09:01:35Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new work_step_events records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createWorkStepEventsRecord } from '@api/work_step_eventsApi';
import type { WorkStepEventsRecord, CreateWorkStepEventsRecordInput } from '@/types/work_step_events';

interface WorkStepEventsCreateFormProps {
  onSuccess: (record: WorkStepEventsRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const WorkStepEventsCreateForm: React.FC<WorkStepEventsCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('work_step_events.create_form');

  const [formData, setFormData] = useState<Partial<CreateWorkStepEventsRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createWorkStepEventsRecord(formData as CreateWorkStepEventsRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="work_step_events-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="work_step_events-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="event_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Event Id *
          </label>
          <input
            type="text"
            id="event_id"
            data-testid="work_step_events-field-event_id"
            value={(formData.event_id as string) || ''}
            onChange={(e) => handleChange('event_id', e.target.value)}
            aria-invalid={!!errors.event_id}
            aria-describedby={errors.event_id ? 'event_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.event_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.event_id && (
            <div
              id="event_id-error"
              role="alert"
              data-testid="work_step_events-field-event_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.event_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="work_unit_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Work Unit Id *
          </label>
          <input
            type="text"
            id="work_unit_id"
            data-testid="work_step_events-field-work_unit_id"
            value={(formData.work_unit_id as string) || ''}
            onChange={(e) => handleChange('work_unit_id', e.target.value)}
            aria-invalid={!!errors.work_unit_id}
            aria-describedby={errors.work_unit_id ? 'work_unit_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.work_unit_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.work_unit_id && (
            <div
              id="work_unit_id-error"
              role="alert"
              data-testid="work_step_events-field-work_unit_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.work_unit_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="sequence_no"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Sequence No *
          </label>
          <input
            type="number"
            id="sequence_no"
            data-testid="work_step_events-field-sequence_no"
            value={(formData.sequence_no as number) || 0}
            onChange={(e) => handleChange('sequence_no', Number(e.target.value))}
            aria-invalid={!!errors.sequence_no}
            aria-describedby={errors.sequence_no ? 'sequence_no-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.sequence_no ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.sequence_no && (
            <div
              id="sequence_no-error"
              role="alert"
              data-testid="work_step_events-field-sequence_no-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.sequence_no}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="event_type"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Event Type *
          </label>
          <input
            type="text"
            id="event_type"
            data-testid="work_step_events-field-event_type"
            value={(formData.event_type as string) || ''}
            onChange={(e) => handleChange('event_type', e.target.value)}
            aria-invalid={!!errors.event_type}
            aria-describedby={errors.event_type ? 'event_type-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.event_type ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.event_type && (
            <div
              id="event_type-error"
              role="alert"
              data-testid="work_step_events-field-event_type-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.event_type}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="timestamp"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Timestamp *
          </label>
          <input
            type="datetime-local"
            id="timestamp"
            data-testid="work_step_events-field-timestamp"
            value={(formData.timestamp as string) || ''}
            onChange={(e) => handleChange('timestamp', e.target.value)}
            aria-invalid={!!errors.timestamp}
            aria-describedby={errors.timestamp ? 'timestamp-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.timestamp ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.timestamp && (
            <div
              id="timestamp-error"
              role="alert"
              data-testid="work_step_events-field-timestamp-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.timestamp}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="actor_type"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Actor Type *
          </label>
          <input
            type="text"
            id="actor_type"
            data-testid="work_step_events-field-actor_type"
            value={(formData.actor_type as string) || ''}
            onChange={(e) => handleChange('actor_type', e.target.value)}
            aria-invalid={!!errors.actor_type}
            aria-describedby={errors.actor_type ? 'actor_type-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.actor_type ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.actor_type && (
            <div
              id="actor_type-error"
              role="alert"
              data-testid="work_step_events-field-actor_type-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.actor_type}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="actor_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Actor Id *
          </label>
          <input
            type="text"
            id="actor_id"
            data-testid="work_step_events-field-actor_id"
            value={(formData.actor_id as string) || ''}
            onChange={(e) => handleChange('actor_id', e.target.value)}
            aria-invalid={!!errors.actor_id}
            aria-describedby={errors.actor_id ? 'actor_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.actor_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.actor_id && (
            <div
              id="actor_id-error"
              role="alert"
              data-testid="work_step_events-field-actor_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.actor_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="state_before"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            State Before *
          </label>
          <input
            type="text"
            id="state_before"
            data-testid="work_step_events-field-state_before"
            value={(formData.state_before as string) || ''}
            onChange={(e) => handleChange('state_before', e.target.value)}
            aria-invalid={!!errors.state_before}
            aria-describedby={errors.state_before ? 'state_before-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.state_before ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.state_before && (
            <div
              id="state_before-error"
              role="alert"
              data-testid="work_step_events-field-state_before-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.state_before}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="state_after"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            State After *
          </label>
          <input
            type="text"
            id="state_after"
            data-testid="work_step_events-field-state_after"
            value={(formData.state_after as string) || ''}
            onChange={(e) => handleChange('state_after', e.target.value)}
            aria-invalid={!!errors.state_after}
            aria-describedby={errors.state_after ? 'state_after-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.state_after ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.state_after && (
            <div
              id="state_after-error"
              role="alert"
              data-testid="work_step_events-field-state_after-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.state_after}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="action_taken"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Action Taken *
          </label>
          <input
            type="text"
            id="action_taken"
            data-testid="work_step_events-field-action_taken"
            value={(formData.action_taken as string) || ''}
            onChange={(e) => handleChange('action_taken', e.target.value)}
            aria-invalid={!!errors.action_taken}
            aria-describedby={errors.action_taken ? 'action_taken-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.action_taken ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.action_taken && (
            <div
              id="action_taken-error"
              role="alert"
              data-testid="work_step_events-field-action_taken-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.action_taken}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="gate_name"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Gate Name *
          </label>
          <input
            type="text"
            id="gate_name"
            data-testid="work_step_events-field-gate_name"
            value={(formData.gate_name as string) || ''}
            onChange={(e) => handleChange('gate_name', e.target.value)}
            aria-invalid={!!errors.gate_name}
            aria-describedby={errors.gate_name ? 'gate_name-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.gate_name ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.gate_name && (
            <div
              id="gate_name-error"
              role="alert"
              data-testid="work_step_events-field-gate_name-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.gate_name}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="gate_result"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Gate Result *
          </label>
          <input
            type="text"
            id="gate_result"
            data-testid="work_step_events-field-gate_result"
            value={(formData.gate_result as string) || ''}
            onChange={(e) => handleChange('gate_result', e.target.value)}
            aria-invalid={!!errors.gate_result}
            aria-describedby={errors.gate_result ? 'gate_result-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.gate_result ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.gate_result && (
            <div
              id="gate_result-error"
              role="alert"
              data-testid="work_step_events-field-gate_result-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.gate_result}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="evidence_ids"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Evidence Ids *
          </label>
          <input
            type="text"
            id="evidence_ids"
            data-testid="work_step_events-field-evidence_ids"
            value={(formData.evidence_ids as string) || ''}
            onChange={(e) => handleChange('evidence_ids', e.target.value)}
            aria-invalid={!!errors.evidence_ids}
            aria-describedby={errors.evidence_ids ? 'evidence_ids-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.evidence_ids ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.evidence_ids && (
            <div
              id="evidence_ids-error"
              role="alert"
              data-testid="work_step_events-field-evidence_ids-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.evidence_ids}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="trace_ids"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Trace Ids *
          </label>
          <input
            type="text"
            id="trace_ids"
            data-testid="work_step_events-field-trace_ids"
            value={(formData.trace_ids as string) || ''}
            onChange={(e) => handleChange('trace_ids', e.target.value)}
            aria-invalid={!!errors.trace_ids}
            aria-describedby={errors.trace_ids ? 'trace_ids-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.trace_ids ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.trace_ids && (
            <div
              id="trace_ids-error"
              role="alert"
              data-testid="work_step_events-field-trace_ids-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.trace_ids}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="decision_ids"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Decision Ids *
          </label>
          <textarea
            id="decision_ids"
            data-testid="work_step_events-field-decision_ids"
            value={(formData.decision_ids as string) || ''}
            onChange={(e) => handleChange('decision_ids', e.target.value)}
            aria-invalid={!!errors.decision_ids}
            aria-describedby={errors.decision_ids ? 'decision_ids-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.decision_ids ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.decision_ids && (
            <div
              id="decision_ids-error"
              role="alert"
              data-testid="work_step_events-field-decision_ids-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.decision_ids}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="error_details"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Error Details *
          </label>
          <input
            type="text"
            id="error_details"
            data-testid="work_step_events-field-error_details"
            value={(formData.error_details as string) || ''}
            onChange={(e) => handleChange('error_details', e.target.value)}
            aria-invalid={!!errors.error_details}
            aria-describedby={errors.error_details ? 'error_details-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.error_details ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.error_details && (
            <div
              id="error_details-error"
              role="alert"
              data-testid="work_step_events-field-error_details-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.error_details}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="metadata"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Metadata *
          </label>
          <textarea
            id="metadata"
            data-testid="work_step_events-field-metadata"
            value={(formData.metadata as string) || ''}
            onChange={(e) => handleChange('metadata', e.target.value)}
            aria-invalid={!!errors.metadata}
            aria-describedby={errors.metadata ? 'metadata-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.metadata ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.metadata && (
            <div
              id="metadata-error"
              role="alert"
              data-testid="work_step_events-field-metadata-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.metadata}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="work_step_events-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="work_step_events-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="work_step_events-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="work_step_events-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

