/**
 * ComplianceAuditCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L82 (compliance_audit)
 * Generated: 2026-03-12T09:01:30Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new compliance_audit records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createComplianceAuditRecord } from '@api/compliance_auditApi';
import type { ComplianceAuditRecord, CreateComplianceAuditRecordInput } from '@/types/compliance_audit';

interface ComplianceAuditCreateFormProps {
  onSuccess: (record: ComplianceAuditRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const ComplianceAuditCreateForm: React.FC<ComplianceAuditCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('compliance_audit.create_form');

  const [formData, setFormData] = useState<Partial<CreateComplianceAuditRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createComplianceAuditRecord(formData as CreateComplianceAuditRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="compliance_audit-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="compliance_audit-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="audit_type"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Audit Type *
          </label>
          <input
            type="text"
            id="audit_type"
            data-testid="compliance_audit-field-audit_type"
            value={(formData.audit_type as string) || ''}
            onChange={(e) => handleChange('audit_type', e.target.value)}
            aria-invalid={!!errors.audit_type}
            aria-describedby={errors.audit_type ? 'audit_type-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.audit_type ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.audit_type && (
            <div
              id="audit_type-error"
              role="alert"
              data-testid="compliance_audit-field-audit_type-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.audit_type}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="audit_framework"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Audit Framework *
          </label>
          <textarea
            id="audit_framework"
            data-testid="compliance_audit-field-audit_framework"
            value={(formData.audit_framework as string) || ''}
            onChange={(e) => handleChange('audit_framework', e.target.value)}
            aria-invalid={!!errors.audit_framework}
            aria-describedby={errors.audit_framework ? 'audit_framework-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.audit_framework ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.audit_framework && (
            <div
              id="audit_framework-error"
              role="alert"
              data-testid="compliance_audit-field-audit_framework-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.audit_framework}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="resource_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Resource Id *
          </label>
          <input
            type="text"
            id="resource_id"
            data-testid="compliance_audit-field-resource_id"
            value={(formData.resource_id as string) || ''}
            onChange={(e) => handleChange('resource_id', e.target.value)}
            aria-invalid={!!errors.resource_id}
            aria-describedby={errors.resource_id ? 'resource_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.resource_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.resource_id && (
            <div
              id="resource_id-error"
              role="alert"
              data-testid="compliance_audit-field-resource_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.resource_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="resource_name"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Resource Name *
          </label>
          <input
            type="text"
            id="resource_name"
            data-testid="compliance_audit-field-resource_name"
            value={(formData.resource_name as string) || ''}
            onChange={(e) => handleChange('resource_name', e.target.value)}
            aria-invalid={!!errors.resource_name}
            aria-describedby={errors.resource_name ? 'resource_name-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.resource_name ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.resource_name && (
            <div
              id="resource_name-error"
              role="alert"
              data-testid="compliance_audit-field-resource_name-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.resource_name}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="resource_type"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Resource Type *
          </label>
          <input
            type="text"
            id="resource_type"
            data-testid="compliance_audit-field-resource_type"
            value={(formData.resource_type as string) || ''}
            onChange={(e) => handleChange('resource_type', e.target.value)}
            aria-invalid={!!errors.resource_type}
            aria-describedby={errors.resource_type ? 'resource_type-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.resource_type ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.resource_type && (
            <div
              id="resource_type-error"
              role="alert"
              data-testid="compliance_audit-field-resource_type-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.resource_type}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="check_name"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Check Name *
          </label>
          <input
            type="text"
            id="check_name"
            data-testid="compliance_audit-field-check_name"
            value={(formData.check_name as string) || ''}
            onChange={(e) => handleChange('check_name', e.target.value)}
            aria-invalid={!!errors.check_name}
            aria-describedby={errors.check_name ? 'check_name-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.check_name ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.check_name && (
            <div
              id="check_name-error"
              role="alert"
              data-testid="compliance_audit-field-check_name-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.check_name}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="check_result"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Check Result *
          </label>
          <input
            type="text"
            id="check_result"
            data-testid="compliance_audit-field-check_result"
            value={(formData.check_result as string) || ''}
            onChange={(e) => handleChange('check_result', e.target.value)}
            aria-invalid={!!errors.check_result}
            aria-describedby={errors.check_result ? 'check_result-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.check_result ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.check_result && (
            <div
              id="check_result-error"
              role="alert"
              data-testid="compliance_audit-field-check_result-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.check_result}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="check_status"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Check Status *
          </label>
          <input
            type="text"
            id="check_status"
            data-testid="compliance_audit-field-check_status"
            value={(formData.check_status as string) || ''}
            onChange={(e) => handleChange('check_status', e.target.value)}
            aria-invalid={!!errors.check_status}
            aria-describedby={errors.check_status ? 'check_status-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.check_status ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.check_status && (
            <div
              id="check_status-error"
              role="alert"
              data-testid="compliance_audit-field-check_status-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.check_status}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="severity"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Severity *
          </label>
          <input
            type="text"
            id="severity"
            data-testid="compliance_audit-field-severity"
            value={(formData.severity as string) || ''}
            onChange={(e) => handleChange('severity', e.target.value)}
            aria-invalid={!!errors.severity}
            aria-describedby={errors.severity ? 'severity-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.severity ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.severity && (
            <div
              id="severity-error"
              role="alert"
              data-testid="compliance_audit-field-severity-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.severity}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="last_checked"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Last Checked *
          </label>
          <input
            type="datetime-local"
            id="last_checked"
            data-testid="compliance_audit-field-last_checked"
            value={(formData.last_checked as string) || ''}
            onChange={(e) => handleChange('last_checked', e.target.value)}
            aria-invalid={!!errors.last_checked}
            aria-describedby={errors.last_checked ? 'last_checked-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.last_checked ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.last_checked && (
            <div
              id="last_checked-error"
              role="alert"
              data-testid="compliance_audit-field-last_checked-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.last_checked}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="evidence_url"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Evidence Url *
          </label>
          <input
            type="text"
            id="evidence_url"
            data-testid="compliance_audit-field-evidence_url"
            value={(formData.evidence_url as string) || ''}
            onChange={(e) => handleChange('evidence_url', e.target.value)}
            aria-invalid={!!errors.evidence_url}
            aria-describedby={errors.evidence_url ? 'evidence_url-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.evidence_url ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.evidence_url && (
            <div
              id="evidence_url-error"
              role="alert"
              data-testid="compliance_audit-field-evidence_url-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.evidence_url}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="evidence_details"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Evidence Details *
          </label>
          <textarea
            id="evidence_details"
            data-testid="compliance_audit-field-evidence_details"
            value={(formData.evidence_details as string) || ''}
            onChange={(e) => handleChange('evidence_details', e.target.value)}
            aria-invalid={!!errors.evidence_details}
            aria-describedby={errors.evidence_details ? 'evidence_details-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.evidence_details ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.evidence_details && (
            <div
              id="evidence_details-error"
              role="alert"
              data-testid="compliance_audit-field-evidence_details-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.evidence_details}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="remediations"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Remediations *
          </label>
          <textarea
            id="remediations"
            data-testid="compliance_audit-field-remediations"
            value={(formData.remediations as string) || ''}
            onChange={(e) => handleChange('remediations', e.target.value)}
            aria-invalid={!!errors.remediations}
            aria-describedby={errors.remediations ? 'remediations-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.remediations ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.remediations && (
            <div
              id="remediations-error"
              role="alert"
              data-testid="compliance_audit-field-remediations-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.remediations}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="last_remediation"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Last Remediation *
          </label>
          <input
            type="text"
            id="last_remediation"
            data-testid="compliance_audit-field-last_remediation"
            value={(formData.last_remediation as string) || ''}
            onChange={(e) => handleChange('last_remediation', e.target.value)}
            aria-invalid={!!errors.last_remediation}
            aria-describedby={errors.last_remediation ? 'last_remediation-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.last_remediation ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.last_remediation && (
            <div
              id="last_remediation-error"
              role="alert"
              data-testid="compliance_audit-field-last_remediation-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.last_remediation}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="remediation_deadline"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Remediation Deadline *
          </label>
          <input
            type="text"
            id="remediation_deadline"
            data-testid="compliance_audit-field-remediation_deadline"
            value={(formData.remediation_deadline as string) || ''}
            onChange={(e) => handleChange('remediation_deadline', e.target.value)}
            aria-invalid={!!errors.remediation_deadline}
            aria-describedby={errors.remediation_deadline ? 'remediation_deadline-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.remediation_deadline ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.remediation_deadline && (
            <div
              id="remediation_deadline-error"
              role="alert"
              data-testid="compliance_audit-field-remediation_deadline-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.remediation_deadline}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="notes"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Notes *
          </label>
          <textarea
            id="notes"
            data-testid="compliance_audit-field-notes"
            value={(formData.notes as string) || ''}
            onChange={(e) => handleChange('notes', e.target.value)}
            aria-invalid={!!errors.notes}
            aria-describedby={errors.notes ? 'notes-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.notes ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.notes && (
            <div
              id="notes-error"
              role="alert"
              data-testid="compliance_audit-field-notes-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.notes}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="compliance_audit-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="compliance_audit-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="compliance_audit-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="compliance_audit-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

