/**
 * RisksCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L74 (risks)
 * Generated: 2026-03-11T18:59:06Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new risks records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createRisksRecord } from '@api/risksApi';
import type { RisksRecord, CreateRisksRecordInput } from '@/types/risks';

interface RisksCreateFormProps {
  onSuccess: (record: RisksRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const RisksCreateForm: React.FC<RisksCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('risks.create_form');

  const [formData, setFormData] = useState<Partial<CreateRisksRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
        if (!formData.project_id) {
      newErrors.project_id = t('errors.required');
    }
    if (!formData.title) {
      newErrors.title = t('errors.required');
    }
    if (!formData.description) {
      newErrors.description = t('errors.required');
    }
    if (!formData.category) {
      newErrors.category = t('errors.required');
    }
    if (!formData.probability) {
      newErrors.probability = t('errors.required');
    }
    if (!formData.impact) {
      newErrors.impact = t('errors.required');
    }
    if (!formData.risk_score) {
      newErrors.risk_score = t('errors.required');
    }
    if (!formData.status) {
      newErrors.status = t('errors.required');
    }
    if (!formData.mitigation) {
      newErrors.mitigation = t('errors.required');
    }
    if (!formData.mitigation_owner) {
      newErrors.mitigation_owner = t('errors.required');
    }
    if (!formData.due_date) {
      newErrors.due_date = t('errors.required');
    }
    if (!formData.sprint_id) {
      newErrors.sprint_id = t('errors.required');
    }
    if (!formData.wbs_ids) {
      newErrors.wbs_ids = t('errors.required');
    }
    if (!formData.notes) {
      newErrors.notes = t('errors.required');
    }
    if (!formData.is_active) {
      newErrors.is_active = t('errors.required');
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createRisksRecord(formData as CreateRisksRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="risks-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="risks-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="project_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Project Id *
          </label>
          <input
            type="text"
            id="project_id"
            data-testid="risks-field-project_id"
            value={(formData.project_id as string) || ''}
            onChange={(e) => handleChange('project_id', e.target.value)}
            aria-invalid={!!errors.project_id}
            aria-describedby={errors.project_id ? 'project_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.project_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.project_id && (
            <div
              id="project_id-error"
              role="alert"
              data-testid="risks-field-project_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.project_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="title"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Title *
          </label>
          <input
            type="text"
            id="title"
            data-testid="risks-field-title"
            value={(formData.title as string) || ''}
            onChange={(e) => handleChange('title', e.target.value)}
            aria-invalid={!!errors.title}
            aria-describedby={errors.title ? 'title-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.title ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.title && (
            <div
              id="title-error"
              role="alert"
              data-testid="risks-field-title-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.title}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="description"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Description *
          </label>
          <textarea
            id="description"
            data-testid="risks-field-description"
            value={(formData.description as string) || ''}
            onChange={(e) => handleChange('description', e.target.value)}
            aria-invalid={!!errors.description}
            aria-describedby={errors.description ? 'description-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.description ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.description && (
            <div
              id="description-error"
              role="alert"
              data-testid="risks-field-description-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.description}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="category"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Category *
          </label>
          <input
            type="text"
            id="category"
            data-testid="risks-field-category"
            value={(formData.category as string) || ''}
            onChange={(e) => handleChange('category', e.target.value)}
            aria-invalid={!!errors.category}
            aria-describedby={errors.category ? 'category-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.category ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.category && (
            <div
              id="category-error"
              role="alert"
              data-testid="risks-field-category-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.category}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="probability"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Probability *
          </label>
          <input
            type="text"
            id="probability"
            data-testid="risks-field-probability"
            value={(formData.probability as string) || ''}
            onChange={(e) => handleChange('probability', e.target.value)}
            aria-invalid={!!errors.probability}
            aria-describedby={errors.probability ? 'probability-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.probability ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.probability && (
            <div
              id="probability-error"
              role="alert"
              data-testid="risks-field-probability-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.probability}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="impact"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Impact *
          </label>
          <input
            type="text"
            id="impact"
            data-testid="risks-field-impact"
            value={(formData.impact as string) || ''}
            onChange={(e) => handleChange('impact', e.target.value)}
            aria-invalid={!!errors.impact}
            aria-describedby={errors.impact ? 'impact-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.impact ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.impact && (
            <div
              id="impact-error"
              role="alert"
              data-testid="risks-field-impact-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.impact}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="risk_score"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Risk Score *
          </label>
          <input
            type="number"
            id="risk_score"
            data-testid="risks-field-risk_score"
            value={(formData.risk_score as number) || 0}
            onChange={(e) => handleChange('risk_score', Number(e.target.value))}
            aria-invalid={!!errors.risk_score}
            aria-describedby={errors.risk_score ? 'risk_score-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.risk_score ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.risk_score && (
            <div
              id="risk_score-error"
              role="alert"
              data-testid="risks-field-risk_score-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.risk_score}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="status"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Status *
          </label>
          <input
            type="text"
            id="status"
            data-testid="risks-field-status"
            value={(formData.status as string) || ''}
            onChange={(e) => handleChange('status', e.target.value)}
            aria-invalid={!!errors.status}
            aria-describedby={errors.status ? 'status-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.status ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.status && (
            <div
              id="status-error"
              role="alert"
              data-testid="risks-field-status-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.status}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="mitigation"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Mitigation *
          </label>
          <input
            type="text"
            id="mitigation"
            data-testid="risks-field-mitigation"
            value={(formData.mitigation as string) || ''}
            onChange={(e) => handleChange('mitigation', e.target.value)}
            aria-invalid={!!errors.mitigation}
            aria-describedby={errors.mitigation ? 'mitigation-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.mitigation ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.mitigation && (
            <div
              id="mitigation-error"
              role="alert"
              data-testid="risks-field-mitigation-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.mitigation}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="mitigation_owner"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Mitigation Owner *
          </label>
          <input
            type="text"
            id="mitigation_owner"
            data-testid="risks-field-mitigation_owner"
            value={(formData.mitigation_owner as string) || ''}
            onChange={(e) => handleChange('mitigation_owner', e.target.value)}
            aria-invalid={!!errors.mitigation_owner}
            aria-describedby={errors.mitigation_owner ? 'mitigation_owner-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.mitigation_owner ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.mitigation_owner && (
            <div
              id="mitigation_owner-error"
              role="alert"
              data-testid="risks-field-mitigation_owner-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.mitigation_owner}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="due_date"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Due Date *
          </label>
          <input
            type="text"
            id="due_date"
            data-testid="risks-field-due_date"
            value={(formData.due_date as string) || ''}
            onChange={(e) => handleChange('due_date', e.target.value)}
            aria-invalid={!!errors.due_date}
            aria-describedby={errors.due_date ? 'due_date-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.due_date ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.due_date && (
            <div
              id="due_date-error"
              role="alert"
              data-testid="risks-field-due_date-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.due_date}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="sprint_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Sprint Id *
          </label>
          <input
            type="text"
            id="sprint_id"
            data-testid="risks-field-sprint_id"
            value={(formData.sprint_id as string) || ''}
            onChange={(e) => handleChange('sprint_id', e.target.value)}
            aria-invalid={!!errors.sprint_id}
            aria-describedby={errors.sprint_id ? 'sprint_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.sprint_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.sprint_id && (
            <div
              id="sprint_id-error"
              role="alert"
              data-testid="risks-field-sprint_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.sprint_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="wbs_ids"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Wbs Ids *
          </label>
          <textarea
            id="wbs_ids"
            data-testid="risks-field-wbs_ids"
            value={(formData.wbs_ids as string) || ''}
            onChange={(e) => handleChange('wbs_ids', e.target.value)}
            aria-invalid={!!errors.wbs_ids}
            aria-describedby={errors.wbs_ids ? 'wbs_ids-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.wbs_ids ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.wbs_ids && (
            <div
              id="wbs_ids-error"
              role="alert"
              data-testid="risks-field-wbs_ids-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.wbs_ids}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="notes"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Notes *
          </label>
          <textarea
            id="notes"
            data-testid="risks-field-notes"
            value={(formData.notes as string) || ''}
            onChange={(e) => handleChange('notes', e.target.value)}
            aria-invalid={!!errors.notes}
            aria-describedby={errors.notes ? 'notes-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.notes ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.notes && (
            <div
              id="notes-error"
              role="alert"
              data-testid="risks-field-notes-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.notes}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="risks-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="risks-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="risks-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="risks-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

