/**
 * WorkOutcomesListView.test.tsx -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L91 (work_outcomes)
 * Generated: 2026-03-11T08:28:20Z
 * Generator: screens-machine-v1.0.0
 * 
 * Unit tests for WorkOutcomesListView component.
 * Based on: Project 31 (EVA Faces) testing patterns
 * 
 * Test Coverage:
 * - Component renders without crash
 * - Loading state displays correctly
 * - Error state displays correctly
 * - Records display in grid
 * - Filter interactions work
 * - Detail drawer opens/closes
 * - Keyboard navigation
 * - Accessibility (ARIA labels, roles)
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { WorkOutcomesListView } from './WorkOutcomesListView';
import { getDefaultWorkOutcomes } from '@eva/data-model-ui';
import { LangProvider } from '@context/LangContext';

// Mock Data Model Views
vi.mock('@eva/data-model-ui', () => ({
  getDefaultWorkOutcomes: vi.fn(),
}));

// Mock NavHeader to simplify tests
vi.mock('@components/NavHeader', () => ({
  NavHeader: () => <div data-testid="nav-header">NavHeader</div>,
}));

const mockRecords = [
  {
    id: 'work_outcomes-001',
    // TODO: Add other fields based on schema
  },
  {
    id: 'work_outcomes-002',
    // TODO: Add other fields based on schema
  },
  {
    id: 'work_outcomes-003',
    // TODO: Add other fields based on schema
  },
];

const renderComponent = (lang: 'en' | 'fr' = 'en') => {
  return render(
    <LangProvider initialLang={lang}>
      <WorkOutcomesListView />
    </LangProvider>
  );
};

describe('WorkOutcomesListView', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe('Loading State', () => {
    it('displays loading message while fetching records', () => {
      vi.mocked(getDefaultWorkOutcomes).mockImplementation(
        () => new Promise(() => {}) // Never resolves
      );

      renderComponent();

      expect(screen.getByTestId('work_outcomes-loading')).toBeInTheDocument();
      expect(screen.getByText(/loading/i)).toBeInTheDocument();
    });
  });

  describe('Error State', () => {
    it('displays error message when fetch fails', async () => {
      const errorMessage = 'Failed to fetch records';
      vi.mocked(getDefaultWorkOutcomes).mockRejectedValue(new Error(errorMessage));

      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-error')).toBeInTheDocument();
      });

      expect(screen.getByText(/failed to load/i)).toBeInTheDocument();
      expect(screen.getByText(errorMessage)).toBeInTheDocument();
    });

    it('displays error message in French when lang=fr', async () => {
      vi.mocked(getDefaultWorkOutcomes).mockRejectedValue(new Error('Test error'));

      renderComponent('fr');

      await waitFor(() => {
        expect(screen.getByText(/erreur de chargement/i)).toBeInTheDocument();
      });
    });
  });

  describe('Success State', () => {
    beforeEach(() => {
      vi.mocked(getDefaultWorkOutcomes).mockResolvedValue(mockRecords);
    });

    it('renders page header with title', async () => {
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-title')).toBeInTheDocument();
      });

      expect(screen.getByTestId('work_outcomes-title')).toHaveTextContent('WorkOutcomes');
    });

    it('displays record count', async () => {
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-count')).toBeInTheDocument();
      });

      expect(screen.getByTestId('work_outcomes-count')).toHaveTextContent('3 records');
    });

    it('displays refreshed timestamp', async () => {
      renderComponent();

      await waitFor(() => {
        expect(screen.getByText(/refreshed/i)).toBeInTheDocument();
      });
    });

    it('renders records grid', async () => {
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-grid')).toBeInTheDocument();
      });

      const grid = screen.getByTestId('work_outcomes-grid');
      expect(within(grid).getAllByRole('article')).toHaveLength(3);
    });

    it('displays filter bar', async () => {
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-filter-bar')).toBeInTheDocument();
      });
    });
  });

  describe('Interactivity', () => {
    beforeEach(() => {
      vi.mocked(getDefaultWorkOutcomes).mockResolvedValue(mockRecords);
    });

    it('opens detail drawer when card clicked', async () => {
      const user = userEvent.setup();
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-grid')).toBeInTheDocument();
      });

      const firstCard = within(screen.getByTestId('work_outcomes-grid')).getAllByRole('article')[0];
      await user.click(firstCard);

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-drawer')).toBeInTheDocument();
      });
    });

    it('closes detail drawer when close button clicked', async () => {
      const user = userEvent.setup();
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-grid')).toBeInTheDocument();
      });

      // Open drawer
      const firstCard = within(screen.getByTestId('work_outcomes-grid')).getAllByRole('article')[0];
      await user.click(firstCard);

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-drawer')).toBeInTheDocument();
      });

      // Close drawer
      const closeButton = screen.getByTestId('work_outcomes-drawer-close');
      await user.click(closeButton);

      await waitFor(() => {
        expect(screen.queryByTestId('work_outcomes-drawer')).not.toBeInTheDocument();
      });
    });

    it('closes detail drawer when Escape pressed', async () => {
      const user = userEvent.setup();
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-grid')).toBeInTheDocument();
      });

      // Open drawer
      const firstCard = within(screen.getByTestId('work_outcomes-grid')).getAllByRole('article')[0];
      await user.click(firstCard);

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-drawer')).toBeInTheDocument();
      });

      // Press Escape
      await user.keyboard('{Escape}');

      await waitFor(() => {
        expect(screen.queryByTestId('work_outcomes-drawer')).not.toBeInTheDocument();
      });
    });

    it('closes detail drawer when backdrop clicked', async () => {
      const user = userEvent.setup();
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-grid')).toBeInTheDocument();
      });

      // Open drawer
      const firstCard = within(screen.getByTestId('work_outcomes-grid')).getAllByRole('article')[0];
      await user.click(firstCard);

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-drawer')).toBeInTheDocument();
      });

      // Click backdrop
      const backdrop = screen.getByTestId('work_outcomes-drawer-backdrop');
      await user.click(backdrop);

      await waitFor(() => {
        expect(screen.queryByTestId('work_outcomes-drawer')).not.toBeInTheDocument();
      });
    });
  });

  describe('No Results', () => {
    it('displays no results message when no records match filters', async () => {
      vi.mocked(getDefaultWorkOutcomes).mockResolvedValue([]);

      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-no-results')).toBeInTheDocument();
      });

      expect(screen.getByText(/no records/i)).toBeInTheDocument();
    });
  });

  describe('Accessibility', () => {
    beforeEach(() => {
      vi.mocked(getDefaultWorkOutcomes).mockResolvedValue(mockRecords);
    });

    it('has proper ARIA labels', async () => {
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-title')).toBeInTheDocument();
      });

      expect(screen.getByRole('region', { name: /page header/i })).toBeInTheDocument();
      expect(screen.getByRole('region', { name: /filters/i })).toBeInTheDocument();
    });

    it('drawer has proper dialog role and aria-modal', async () => {
      const user = userEvent.setup();
      renderComponent();

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-grid')).toBeInTheDocument();
      });

      const firstCard = within(screen.getByTestId('work_outcomes-grid')).getAllByRole('article')[0];
      await user.click(firstCard);

      await waitFor(() => {
        expect(screen.getByRole('dialog')).toBeInTheDocument();
      });

      const dialog = screen.getByRole('dialog');
      expect(dialog).toHaveAttribute('aria-modal', 'true');
    });
  });

  describe('i18n', () => {
    beforeEach(() => {
      vi.mocked(getDefaultWorkOutcomes).mockResolvedValue(mockRecords);
    });

    it('displays French translations when lang=fr', async () => {
      renderComponent('fr');

      await waitFor(() => {
        expect(screen.getByTestId('work_outcomes-title')).toBeInTheDocument();
      });

      // Check for French text (adjust based on actual translations)
      expect(screen.getByTestId('work_outcomes-count')).toHaveTextContent('enregistrements');
    });
  });
});

