/**
 * CostAllocationCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L44 (cost_allocation)
 * Generated: 2026-03-12T09:01:03Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new cost_allocation records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createCostAllocationRecord } from '@api/cost_allocationApi';
import type { CostAllocationRecord, CreateCostAllocationRecordInput } from '@/types/cost_allocation';

interface CostAllocationCreateFormProps {
  onSuccess: (record: CostAllocationRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const CostAllocationCreateForm: React.FC<CostAllocationCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('cost_allocation.create_form');

  const [formData, setFormData] = useState<Partial<CreateCostAllocationRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createCostAllocationRecord(formData as CreateCostAllocationRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="cost_allocation-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="cost_allocation-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="billing_period"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Billing Period *
          </label>
          <input
            type="text"
            id="billing_period"
            data-testid="cost_allocation-field-billing_period"
            value={(formData.billing_period as string) || ''}
            onChange={(e) => handleChange('billing_period', e.target.value)}
            aria-invalid={!!errors.billing_period}
            aria-describedby={errors.billing_period ? 'billing_period-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.billing_period ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.billing_period && (
            <div
              id="billing_period-error"
              role="alert"
              data-testid="cost_allocation-field-billing_period-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.billing_period}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="cost_center"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Cost Center *
          </label>
          <input
            type="text"
            id="cost_center"
            data-testid="cost_allocation-field-cost_center"
            value={(formData.cost_center as string) || ''}
            onChange={(e) => handleChange('cost_center', e.target.value)}
            aria-invalid={!!errors.cost_center}
            aria-describedby={errors.cost_center ? 'cost_center-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.cost_center ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.cost_center && (
            <div
              id="cost_center-error"
              role="alert"
              data-testid="cost_allocation-field-cost_center-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.cost_center}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="project_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Project Id *
          </label>
          <input
            type="text"
            id="project_id"
            data-testid="cost_allocation-field-project_id"
            value={(formData.project_id as string) || ''}
            onChange={(e) => handleChange('project_id', e.target.value)}
            aria-invalid={!!errors.project_id}
            aria-describedby={errors.project_id ? 'project_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.project_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.project_id && (
            <div
              id="project_id-error"
              role="alert"
              data-testid="cost_allocation-field-project_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.project_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="total_cost_usd"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Total Cost Usd *
          </label>
          <input
            type="number"
            id="total_cost_usd"
            data-testid="cost_allocation-field-total_cost_usd"
            value={(formData.total_cost_usd as number) || 0}
            onChange={(e) => handleChange('total_cost_usd', Number(e.target.value))}
            aria-invalid={!!errors.total_cost_usd}
            aria-describedby={errors.total_cost_usd ? 'total_cost_usd-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.total_cost_usd ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.total_cost_usd && (
            <div
              id="total_cost_usd-error"
              role="alert"
              data-testid="cost_allocation-field-total_cost_usd-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.total_cost_usd}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="forecast_month_end_usd"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Forecast Month End Usd *
          </label>
          <input
            type="number"
            id="forecast_month_end_usd"
            data-testid="cost_allocation-field-forecast_month_end_usd"
            value={(formData.forecast_month_end_usd as number) || 0}
            onChange={(e) => handleChange('forecast_month_end_usd', Number(e.target.value))}
            aria-invalid={!!errors.forecast_month_end_usd}
            aria-describedby={errors.forecast_month_end_usd ? 'forecast_month_end_usd-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.forecast_month_end_usd ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.forecast_month_end_usd && (
            <div
              id="forecast_month_end_usd-error"
              role="alert"
              data-testid="cost_allocation-field-forecast_month_end_usd-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.forecast_month_end_usd}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="budget_allocated_usd"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Budget Allocated Usd *
          </label>
          <input
            type="number"
            id="budget_allocated_usd"
            data-testid="cost_allocation-field-budget_allocated_usd"
            value={(formData.budget_allocated_usd as number) || 0}
            onChange={(e) => handleChange('budget_allocated_usd', Number(e.target.value))}
            aria-invalid={!!errors.budget_allocated_usd}
            aria-describedby={errors.budget_allocated_usd ? 'budget_allocated_usd-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.budget_allocated_usd ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.budget_allocated_usd && (
            <div
              id="budget_allocated_usd-error"
              role="alert"
              data-testid="cost_allocation-field-budget_allocated_usd-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.budget_allocated_usd}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="budget_consumed_percent"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Budget Consumed Percent *
          </label>
          <input
            type="number"
            id="budget_consumed_percent"
            data-testid="cost_allocation-field-budget_consumed_percent"
            value={(formData.budget_consumed_percent as number) || 0}
            onChange={(e) => handleChange('budget_consumed_percent', Number(e.target.value))}
            aria-invalid={!!errors.budget_consumed_percent}
            aria-describedby={errors.budget_consumed_percent ? 'budget_consumed_percent-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.budget_consumed_percent ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.budget_consumed_percent && (
            <div
              id="budget_consumed_percent-error"
              role="alert"
              data-testid="cost_allocation-field-budget_consumed_percent-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.budget_consumed_percent}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="resource_breakdown"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Resource Breakdown *
          </label>
          <textarea
            id="resource_breakdown"
            data-testid="cost_allocation-field-resource_breakdown"
            value={(formData.resource_breakdown as string) || ''}
            onChange={(e) => handleChange('resource_breakdown', e.target.value)}
            aria-invalid={!!errors.resource_breakdown}
            aria-describedby={errors.resource_breakdown ? 'resource_breakdown-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.resource_breakdown ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.resource_breakdown && (
            <div
              id="resource_breakdown-error"
              role="alert"
              data-testid="cost_allocation-field-resource_breakdown-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.resource_breakdown}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="cost_drivers"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Cost Drivers *
          </label>
          <textarea
            id="cost_drivers"
            data-testid="cost_allocation-field-cost_drivers"
            value={(formData.cost_drivers as string) || ''}
            onChange={(e) => handleChange('cost_drivers', e.target.value)}
            aria-invalid={!!errors.cost_drivers}
            aria-describedby={errors.cost_drivers ? 'cost_drivers-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.cost_drivers ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.cost_drivers && (
            <div
              id="cost_drivers-error"
              role="alert"
              data-testid="cost_allocation-field-cost_drivers-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.cost_drivers}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="optimization_opportunities"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Optimization Opportunities *
          </label>
          <textarea
            id="optimization_opportunities"
            data-testid="cost_allocation-field-optimization_opportunities"
            value={(formData.optimization_opportunities as string) || ''}
            onChange={(e) => handleChange('optimization_opportunities', e.target.value)}
            aria-invalid={!!errors.optimization_opportunities}
            aria-describedby={errors.optimization_opportunities ? 'optimization_opportunities-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.optimization_opportunities ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.optimization_opportunities && (
            <div
              id="optimization_opportunities-error"
              role="alert"
              data-testid="cost_allocation-field-optimization_opportunities-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.optimization_opportunities}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="cost_allocation-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="cost_allocation-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="cost_allocation-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="cost_allocation-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

