/**
 * TestCasesCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L38 (test_cases)
 * Generated: 2026-03-12T09:00:59Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new test_cases records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createTestCasesRecord } from '@api/test_casesApi';
import type { TestCasesRecord, CreateTestCasesRecordInput } from '@/types/test_cases';

interface TestCasesCreateFormProps {
  onSuccess: (record: TestCasesRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const TestCasesCreateForm: React.FC<TestCasesCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('test_cases.create_form');

  const [formData, setFormData] = useState<Partial<CreateTestCasesRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createTestCasesRecord(formData as CreateTestCasesRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="test_cases-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="test_cases-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="story_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Story Id *
          </label>
          <input
            type="text"
            id="story_id"
            data-testid="test_cases-field-story_id"
            value={(formData.story_id as string) || ''}
            onChange={(e) => handleChange('story_id', e.target.value)}
            aria-invalid={!!errors.story_id}
            aria-describedby={errors.story_id ? 'story_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.story_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.story_id && (
            <div
              id="story_id-error"
              role="alert"
              data-testid="test_cases-field-story_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.story_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="service_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Service Id *
          </label>
          <input
            type="text"
            id="service_id"
            data-testid="test_cases-field-service_id"
            value={(formData.service_id as string) || ''}
            onChange={(e) => handleChange('service_id', e.target.value)}
            aria-invalid={!!errors.service_id}
            aria-describedby={errors.service_id ? 'service_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.service_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.service_id && (
            <div
              id="service_id-error"
              role="alert"
              data-testid="test_cases-field-service_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.service_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="test_name"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Test Name *
          </label>
          <input
            type="text"
            id="test_name"
            data-testid="test_cases-field-test_name"
            value={(formData.test_name as string) || ''}
            onChange={(e) => handleChange('test_name', e.target.value)}
            aria-invalid={!!errors.test_name}
            aria-describedby={errors.test_name ? 'test_name-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.test_name ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.test_name && (
            <div
              id="test_name-error"
              role="alert"
              data-testid="test_cases-field-test_name-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.test_name}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="test_type"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Test Type *
          </label>
          <input
            type="text"
            id="test_type"
            data-testid="test_cases-field-test_type"
            value={(formData.test_type as string) || ''}
            onChange={(e) => handleChange('test_type', e.target.value)}
            aria-invalid={!!errors.test_type}
            aria-describedby={errors.test_type ? 'test_type-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.test_type ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.test_type && (
            <div
              id="test_type-error"
              role="alert"
              data-testid="test_cases-field-test_type-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.test_type}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="preconditions"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Preconditions *
          </label>
          <input
            type="text"
            id="preconditions"
            data-testid="test_cases-field-preconditions"
            value={(formData.preconditions as string) || ''}
            onChange={(e) => handleChange('preconditions', e.target.value)}
            aria-invalid={!!errors.preconditions}
            aria-describedby={errors.preconditions ? 'preconditions-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.preconditions ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.preconditions && (
            <div
              id="preconditions-error"
              role="alert"
              data-testid="test_cases-field-preconditions-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.preconditions}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="test_steps"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Test Steps *
          </label>
          <textarea
            id="test_steps"
            data-testid="test_cases-field-test_steps"
            value={(formData.test_steps as string) || ''}
            onChange={(e) => handleChange('test_steps', e.target.value)}
            aria-invalid={!!errors.test_steps}
            aria-describedby={errors.test_steps ? 'test_steps-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.test_steps ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.test_steps && (
            <div
              id="test_steps-error"
              role="alert"
              data-testid="test_cases-field-test_steps-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.test_steps}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="expected_result"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Expected Result *
          </label>
          <input
            type="text"
            id="expected_result"
            data-testid="test_cases-field-expected_result"
            value={(formData.expected_result as string) || ''}
            onChange={(e) => handleChange('expected_result', e.target.value)}
            aria-invalid={!!errors.expected_result}
            aria-describedby={errors.expected_result ? 'expected_result-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.expected_result ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.expected_result && (
            <div
              id="expected_result-error"
              role="alert"
              data-testid="test_cases-field-expected_result-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.expected_result}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="status"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Status *
          </label>
          <input
            type="text"
            id="status"
            data-testid="test_cases-field-status"
            value={(formData.status as string) || ''}
            onChange={(e) => handleChange('status', e.target.value)}
            aria-invalid={!!errors.status}
            aria-describedby={errors.status ? 'status-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.status ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.status && (
            <div
              id="status-error"
              role="alert"
              data-testid="test_cases-field-status-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.status}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="execution_count"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Execution Count *
          </label>
          <input
            type="number"
            id="execution_count"
            data-testid="test_cases-field-execution_count"
            value={(formData.execution_count as number) || 0}
            onChange={(e) => handleChange('execution_count', Number(e.target.value))}
            aria-invalid={!!errors.execution_count}
            aria-describedby={errors.execution_count ? 'execution_count-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.execution_count ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.execution_count && (
            <div
              id="execution_count-error"
              role="alert"
              data-testid="test_cases-field-execution_count-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.execution_count}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="last_run"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Last Run *
          </label>
          <input
            type="datetime-local"
            id="last_run"
            data-testid="test_cases-field-last_run"
            value={(formData.last_run as string) || ''}
            onChange={(e) => handleChange('last_run', e.target.value)}
            aria-invalid={!!errors.last_run}
            aria-describedby={errors.last_run ? 'last_run-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.last_run ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.last_run && (
            <div
              id="last_run-error"
              role="alert"
              data-testid="test_cases-field-last_run-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.last_run}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="test_cases-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="test_cases-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="test_cases-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="test_cases-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

