/**
 * ModelTelemetryCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L28 (model_telemetry)
 * Generated: 2026-03-12T09:00:53Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new model_telemetry records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createModelTelemetryRecord } from '@api/model_telemetryApi';
import type { ModelTelemetryRecord, CreateModelTelemetryRecordInput } from '@/types/model_telemetry';

interface ModelTelemetryCreateFormProps {
  onSuccess: (record: ModelTelemetryRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const ModelTelemetryCreateForm: React.FC<ModelTelemetryCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('model_telemetry.create_form');

  const [formData, setFormData] = useState<Partial<CreateModelTelemetryRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createModelTelemetryRecord(formData as CreateModelTelemetryRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="model_telemetry-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="model_telemetry-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="persona_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Persona Id *
          </label>
          <input
            type="text"
            id="persona_id"
            data-testid="model_telemetry-field-persona_id"
            value={(formData.persona_id as string) || ''}
            onChange={(e) => handleChange('persona_id', e.target.value)}
            aria-invalid={!!errors.persona_id}
            aria-describedby={errors.persona_id ? 'persona_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.persona_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.persona_id && (
            <div
              id="persona_id-error"
              role="alert"
              data-testid="model_telemetry-field-persona_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.persona_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="workflow_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Workflow Id *
          </label>
          <input
            type="text"
            id="workflow_id"
            data-testid="model_telemetry-field-workflow_id"
            value={(formData.workflow_id as string) || ''}
            onChange={(e) => handleChange('workflow_id', e.target.value)}
            aria-invalid={!!errors.workflow_id}
            aria-describedby={errors.workflow_id ? 'workflow_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.workflow_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.workflow_id && (
            <div
              id="workflow_id-error"
              role="alert"
              data-testid="model_telemetry-field-workflow_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.workflow_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="model"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Model *
          </label>
          <input
            type="text"
            id="model"
            data-testid="model_telemetry-field-model"
            value={(formData.model as string) || ''}
            onChange={(e) => handleChange('model', e.target.value)}
            aria-invalid={!!errors.model}
            aria-describedby={errors.model ? 'model-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.model ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.model && (
            <div
              id="model-error"
              role="alert"
              data-testid="model_telemetry-field-model-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.model}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="prompt_tokens"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Prompt Tokens *
          </label>
          <input
            type="number"
            id="prompt_tokens"
            data-testid="model_telemetry-field-prompt_tokens"
            value={(formData.prompt_tokens as number) || 0}
            onChange={(e) => handleChange('prompt_tokens', Number(e.target.value))}
            aria-invalid={!!errors.prompt_tokens}
            aria-describedby={errors.prompt_tokens ? 'prompt_tokens-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.prompt_tokens ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.prompt_tokens && (
            <div
              id="prompt_tokens-error"
              role="alert"
              data-testid="model_telemetry-field-prompt_tokens-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.prompt_tokens}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="completion_tokens"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Completion Tokens *
          </label>
          <input
            type="number"
            id="completion_tokens"
            data-testid="model_telemetry-field-completion_tokens"
            value={(formData.completion_tokens as number) || 0}
            onChange={(e) => handleChange('completion_tokens', Number(e.target.value))}
            aria-invalid={!!errors.completion_tokens}
            aria-describedby={errors.completion_tokens ? 'completion_tokens-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.completion_tokens ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.completion_tokens && (
            <div
              id="completion_tokens-error"
              role="alert"
              data-testid="model_telemetry-field-completion_tokens-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.completion_tokens}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="total_tokens"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Total Tokens *
          </label>
          <input
            type="number"
            id="total_tokens"
            data-testid="model_telemetry-field-total_tokens"
            value={(formData.total_tokens as number) || 0}
            onChange={(e) => handleChange('total_tokens', Number(e.target.value))}
            aria-invalid={!!errors.total_tokens}
            aria-describedby={errors.total_tokens ? 'total_tokens-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.total_tokens ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.total_tokens && (
            <div
              id="total_tokens-error"
              role="alert"
              data-testid="model_telemetry-field-total_tokens-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.total_tokens}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="latency_ms"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Latency Ms *
          </label>
          <input
            type="number"
            id="latency_ms"
            data-testid="model_telemetry-field-latency_ms"
            value={(formData.latency_ms as number) || 0}
            onChange={(e) => handleChange('latency_ms', Number(e.target.value))}
            aria-invalid={!!errors.latency_ms}
            aria-describedby={errors.latency_ms ? 'latency_ms-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.latency_ms ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.latency_ms && (
            <div
              id="latency_ms-error"
              role="alert"
              data-testid="model_telemetry-field-latency_ms-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.latency_ms}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="temperature"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Temperature *
          </label>
          <input
            type="number"
            id="temperature"
            data-testid="model_telemetry-field-temperature"
            value={(formData.temperature as number) || 0}
            onChange={(e) => handleChange('temperature', Number(e.target.value))}
            aria-invalid={!!errors.temperature}
            aria-describedby={errors.temperature ? 'temperature-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.temperature ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.temperature && (
            <div
              id="temperature-error"
              role="alert"
              data-testid="model_telemetry-field-temperature-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.temperature}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="timestamp"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Timestamp *
          </label>
          <input
            type="datetime-local"
            id="timestamp"
            data-testid="model_telemetry-field-timestamp"
            value={(formData.timestamp as string) || ''}
            onChange={(e) => handleChange('timestamp', e.target.value)}
            aria-invalid={!!errors.timestamp}
            aria-describedby={errors.timestamp ? 'timestamp-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.timestamp ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.timestamp && (
            <div
              id="timestamp-error"
              role="alert"
              data-testid="model_telemetry-field-timestamp-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.timestamp}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="model_telemetry-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="model_telemetry-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="model_telemetry-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="model_telemetry-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

