/**
 * ValidationRulesCreateForm -- Auto-generated by Screens Machine v1.0.0
 * 
 * Data Model Layer: L80 (validation_rules)
 * Generated: 2026-03-12T09:01:28Z
 * Generator: screens-machine-v1.0.0
 * 
 * Form for creating new validation_rules records with validation and error handling.
 * 
 * Features:
 * - Client-side validation
 * - Field-level error messages
 * - Submit/Cancel actions
 * - Accessible form markup (labels, aria-describedby)
 * - WCAG 2.1 Level AA compliant
 */

import React, { useState } from 'react';
import { useLiterals } from '@hooks/useLiterals';
import { createValidationRulesRecord } from '@api/validation_rulesApi';
import type { ValidationRulesRecord, CreateValidationRulesRecordInput } from '@/types/validation_rules';

interface ValidationRulesCreateFormProps {
  onSuccess: (record: ValidationRulesRecord) => void;
  onCancel: () => void;
}

// GC Design System colors
const GC_TEXT    = '#0b0c0e';
const GC_MUTED   = '#505a5f';
const GC_BORDER  = '#b1b4b6';
const GC_SURFACE = '#f8f8f8';
const GC_BLUE    = '#1d70b8';
const GC_ERROR   = '#d4351c';
const GC_SUCCESS = '#00703c';

export const ValidationRulesCreateForm: React.FC<ValidationRulesCreateFormProps> = ({ onSuccess, onCancel }) => {
  const t = useLiterals('validation_rules.create_form');

  const [formData, setFormData] = useState<Partial<CreateValidationRulesRecordInput>>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    
    // TODO: Add validation rules based on schema
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    if (!validate()) return;

    setSubmitting(true);
    try {
      const record = await createValidationRulesRecord(formData as CreateValidationRulesRecordInput);
      onSuccess(record);
    } catch (error) {
      setSubmitError(error instanceof Error ? error.message : 'Unknown error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => {
        const next = { ...prev };
        delete next[field];
        return next;
      });
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      data-testid="validation_rules-create-form"
      style={{
        maxWidth: 600,
        margin: '0 auto',
        padding: '24px',
        background: '#fff',
        border: `1px solid ${GC_BORDER}`,
        borderRadius: 4,
        fontFamily: 'Noto Sans, sans-serif',
      }}
    >
      {/* Form header */}
      <h2 style={{ margin: '0 0 24px', fontSize: '1.25rem', fontWeight: 700, color: GC_TEXT }}>
        {t('title')}
      </h2>

      {/* Submit error banner */}
      {submitError && (
        <div
          role="alert"
          data-testid="validation_rules-submit-error"
          style={{
            padding: '12px 16px',
            marginBottom: 20,
            background: '#fef7f7',
            border: `1px solid ${GC_ERROR}`,
            borderRadius: 4,
            color: GC_ERROR,
            fontSize: '0.875rem',
          }}
        >
          <strong>{t('messages.error')}:</strong> {submitError}
        </div>
      )}

      {/* Form fields (auto-generated from schema) */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <div>
          <label
            htmlFor="project_id"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Project Id *
          </label>
          <input
            type="text"
            id="project_id"
            data-testid="validation_rules-field-project_id"
            value={(formData.project_id as string) || ''}
            onChange={(e) => handleChange('project_id', e.target.value)}
            aria-invalid={!!errors.project_id}
            aria-describedby={errors.project_id ? 'project_id-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.project_id ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.project_id && (
            <div
              id="project_id-error"
              role="alert"
              data-testid="validation_rules-field-project_id-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.project_id}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="project_name"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Project Name *
          </label>
          <input
            type="text"
            id="project_name"
            data-testid="validation_rules-field-project_name"
            value={(formData.project_name as string) || ''}
            onChange={(e) => handleChange('project_name', e.target.value)}
            aria-invalid={!!errors.project_name}
            aria-describedby={errors.project_name ? 'project_name-error' : undefined}
            disabled={submitting}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.project_name ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
            }}
          />
          {errors.project_name && (
            <div
              id="project_name-error"
              role="alert"
              data-testid="validation_rules-field-project_name-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.project_name}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="description"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Description *
          </label>
          <textarea
            id="description"
            data-testid="validation_rules-field-description"
            value={(formData.description as string) || ''}
            onChange={(e) => handleChange('description', e.target.value)}
            aria-invalid={!!errors.description}
            aria-describedby={errors.description ? 'description-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.description ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.description && (
            <div
              id="description-error"
              role="alert"
              data-testid="validation_rules-field-description-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.description}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="schema_validation"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Schema Validation *
          </label>
          <textarea
            id="schema_validation"
            data-testid="validation_rules-field-schema_validation"
            value={(formData.schema_validation as string) || ''}
            onChange={(e) => handleChange('schema_validation', e.target.value)}
            aria-invalid={!!errors.schema_validation}
            aria-describedby={errors.schema_validation ? 'schema_validation-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.schema_validation ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.schema_validation && (
            <div
              id="schema_validation-error"
              role="alert"
              data-testid="validation_rules-field-schema_validation-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.schema_validation}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="data_integrity"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Data Integrity *
          </label>
          <textarea
            id="data_integrity"
            data-testid="validation_rules-field-data_integrity"
            value={(formData.data_integrity as string) || ''}
            onChange={(e) => handleChange('data_integrity', e.target.value)}
            aria-invalid={!!errors.data_integrity}
            aria-describedby={errors.data_integrity ? 'data_integrity-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.data_integrity ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.data_integrity && (
            <div
              id="data_integrity-error"
              role="alert"
              data-testid="validation_rules-field-data_integrity-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.data_integrity}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="compliance_gates"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Compliance Gates *
          </label>
          <textarea
            id="compliance_gates"
            data-testid="validation_rules-field-compliance_gates"
            value={(formData.compliance_gates as string) || ''}
            onChange={(e) => handleChange('compliance_gates', e.target.value)}
            aria-invalid={!!errors.compliance_gates}
            aria-describedby={errors.compliance_gates ? 'compliance_gates-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.compliance_gates ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.compliance_gates && (
            <div
              id="compliance_gates-error"
              role="alert"
              data-testid="validation_rules-field-compliance_gates-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.compliance_gates}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="validation_workflow"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Validation Workflow *
          </label>
          <textarea
            id="validation_workflow"
            data-testid="validation_rules-field-validation_workflow"
            value={(formData.validation_workflow as string) || ''}
            onChange={(e) => handleChange('validation_workflow', e.target.value)}
            aria-invalid={!!errors.validation_workflow}
            aria-describedby={errors.validation_workflow ? 'validation_workflow-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.validation_workflow ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.validation_workflow && (
            <div
              id="validation_workflow-error"
              role="alert"
              data-testid="validation_rules-field-validation_workflow-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.validation_workflow}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="validation_scripts"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Validation Scripts
          </label>
          <textarea
            id="validation_scripts"
            data-testid="validation_rules-field-validation_scripts"
            value={(formData.validation_scripts as string) || ''}
            onChange={(e) => handleChange('validation_scripts', e.target.value)}
            aria-invalid={!!errors.validation_scripts}
            aria-describedby={errors.validation_scripts ? 'validation_scripts-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.validation_scripts ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.validation_scripts && (
            <div
              id="validation_scripts-error"
              role="alert"
              data-testid="validation_rules-field-validation_scripts-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.validation_scripts}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="error_handling"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Error Handling *
          </label>
          <textarea
            id="error_handling"
            data-testid="validation_rules-field-error_handling"
            value={(formData.error_handling as string) || ''}
            onChange={(e) => handleChange('error_handling', e.target.value)}
            aria-invalid={!!errors.error_handling}
            aria-describedby={errors.error_handling ? 'error_handling-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.error_handling ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.error_handling && (
            <div
              id="error_handling-error"
              role="alert"
              data-testid="validation_rules-field-error_handling-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.error_handling}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="custom_validators"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Custom Validators
          </label>
          <textarea
            id="custom_validators"
            data-testid="validation_rules-field-custom_validators"
            value={(formData.custom_validators as string) || ''}
            onChange={(e) => handleChange('custom_validators', e.target.value)}
            aria-invalid={!!errors.custom_validators}
            aria-describedby={errors.custom_validators ? 'custom_validators-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.custom_validators ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.custom_validators && (
            <div
              id="custom_validators-error"
              role="alert"
              data-testid="validation_rules-field-custom_validators-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.custom_validators}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="audit_trail"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Audit Trail
          </label>
          <textarea
            id="audit_trail"
            data-testid="validation_rules-field-audit_trail"
            value={(formData.audit_trail as string) || ''}
            onChange={(e) => handleChange('audit_trail', e.target.value)}
            aria-invalid={!!errors.audit_trail}
            aria-describedby={errors.audit_trail ? 'audit_trail-error' : undefined}
            disabled={submitting}
            rows={4}
            style={{
              width: '100%',
              padding: '8px 12px',
              border: `1px solid ${errors.audit_trail ? GC_ERROR : GC_BORDER}`,
              borderRadius: 4,
              fontSize: '0.875rem',
              fontFamily: 'inherit',
              resize: 'vertical',
            }}
          />
          {errors.audit_trail && (
            <div
              id="audit_trail-error"
              role="alert"
              data-testid="validation_rules-field-audit_trail-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.audit_trail}
            </div>
          )}
        </div>

        <div>
          <label
            htmlFor="is_active"
            style={{
              display: 'block',
              marginBottom: 4,
              fontSize: '0.875rem',
              fontWeight: 600,
              color: GC_TEXT,
            }}
          >
            Is Active *
          </label>
          <input
            type="checkbox"
            id="is_active"
            data-testid="validation_rules-field-is_active"
            checked={(formData.is_active as boolean) || false}
            onChange={(e) => handleChange('is_active', e.target.checked)}
            aria-invalid={!!errors.is_active}
            aria-describedby={errors.is_active ? 'is_active-error' : undefined}
            disabled={submitting}
            style={{
              width: '18px',
              height: '18px',
              cursor: 'pointer',
            }}
          />
          {errors.is_active && (
            <div
              id="is_active-error"
              role="alert"
              data-testid="validation_rules-field-is_active-error"
              style={{
                marginTop: 4,
                fontSize: '0.75rem',
                color: GC_ERROR,
              }}
            >
              {errors.is_active}
            </div>
          )}
        </div>
      </div>

      {/* Form actions */}
      <div style={{ display: 'flex', gap: 12, marginTop: 24, justifyContent: 'flex-end' }}>
        <button
          type="button"
          onClick={onCancel}
          disabled={submitting}
          data-testid="validation_rules-cancel-button"
          style={{
            padding: '10px 20px',
            background: '#fff',
            color: GC_TEXT,
            border: `1px solid ${GC_BORDER}`,
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
            opacity: submitting ? 0.6 : 1,
          }}
        >
          {t('actions.cancel')}
        </button>
        <button
          type="submit"
          disabled={submitting}
          data-testid="validation_rules-submit-button"
          style={{
            padding: '10px 20px',
            background: submitting ? GC_MUTED : GC_BLUE,
            color: '#fff',
            border: 'none',
            borderRadius: 4,
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: submitting ? 'not-allowed' : 'pointer',
          }}
        >
          {submitting ? t('messages.creating') : t('actions.submit')}
        </button>
      </div>
    </form>
  );
};

